/**
 * Extended Ingredient Database - Base de conocimiento expandida
 * Fitoterapia, Homeopatía, Suplementos y más
 */

export interface ExtendedIngredientInfo {
  id: string;
  name: string;
  scientificName?: string;
  category: 'homeopatia' | 'fitoterapia' | 'suplemento' | 'mineral' | 'vitamin' | 'aminoacido' | 'otro';
  origin: {
    type: 'planta' | 'mineral' | 'animal' | 'sintetico' | 'microorganismo';
    description: string;
  };
  description: string;
  mechanism: string;
  indications: string[];
  contraindications: string[];
  interactions: string[];
  dosage: string;
  sideEffects?: string[];
  synonyms: string[];
  warnings?: string[];
}

// Base de datos extendida de Homeopatía
export const HOMEOPATHY_DATABASE: Record<string, ExtendedIngredientInfo> = {
  // Remedios del Sistema Nervioso
  'aconitum': {
    id: 'aconitum',
    name: 'Aconitum Napellus',
    scientificName: 'Aconitum napellus',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Planta de la familia Ranunculaceae. Nativa de Europa. Muy tóxica en estado bruto.',
    },
    description: 'Remedio para estados agudos con inicio súbito, miedo, ansiedad y fiebre alta.',
    mechanism: 'Modula el sistema nervioso simpático. Regula la respuesta de miedo y la fiebre.',
    indications: ['Ansiedad aguda', 'Miedo intenso', 'Fiebre de inicio súbito', 'Insomnio por preocupación', 'Shock emocional', 'Taquicardia por miedo', 'Cólicos renales agudos'],
    contraindications: ['Ninguna absoluta bajo supervisión médica'],
    interactions: ['Sin interacciones conocidas con otros remedios homeopáticos'],
    dosage: 'CH 6 a CH 30: 3-5 gránulos cada 15-30 min en crisis agudas.',
    synonyms: ['aconit', 'acónito', 'wolfsbane', 'monkshood'],
    warnings: ['TÓXICO en estado bruto', 'Solo usar diluciones homeopáticas'],
  },
  'apis': {
    id: 'apis',
    name: 'Apis Mellifica',
    scientificName: 'Apis mellifera',
    category: 'homeopatia',
    origin: {
      type: 'animal',
      description: 'Abeja obrera. Tintura madre de abeja entera.',
    },
    description: 'Remedio para inflamaciones con edema, picazón y sensación de ardor que mejora con frío.',
    mechanism: 'Modula la respuesta inflamatoria alérgica. Reduce edema y permeabilidad capilar.',
    indications: ['Picaduras de insectos', 'Urticaria con edema', 'Angioedema', 'Conjuntivitis алергическая', 'Otitis media', 'Cistitis', 'Edema de glotis'],
    contraindications: ['Hipersensibilidad a productos apícolas'],
    interactions: ['No dar junto con Rhus toxicodendron'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 2-4 veces al día.',
    synonyms: ['apis mellifica', 'abeja', 'honey bee'],
    warnings: ['Reacción alérgica rara pero posible'],
  },
  'arnica': {
    id: 'arnica',
    name: 'Árnica Montana',
    scientificName: 'Arnica montana',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Planta herbácea de las montañas de Europa. Familia Asteraceae.',
    },
    description: 'Remedio para traumatismos, golpes, fatiga muscular y post-operatorio.',
    mechanism: 'Modula la respuesta inflamatoria y el dolor postraumático. Reduce hematomas y edema.',
    indications: ['Traumatismos y golpes', 'Fatiga muscular', 'Hematomas y moretones', 'Post-operatorio dental', 'Esguinces y distensiones', 'Contusiones', 'Dolores por sobreesfuerzo'],
    contraindications: ['Hipersensibilidad a Asteraceae', 'No aplicar sobre heridas abiertas', 'Niños menores de 3 años (tópico)'],
    interactions: ['Puede potenciar efectos de anticoagulantes'],
    dosage: 'CH 5 a CH 9: 3-5 gránulos cada 2-4 horas en fase aguda. Tópico: gel 2-3 veces al día.',
    synonyms: ['arnica montana', 'tabaco de montaña', 'hierba de las caídas', 'leopard\'s bane'],
    warnings: ['Solo uso tópico en lesiones cerradas', 'No exceder dosis recomendadas'],
  },
  'arsenicum-album': {
    id: 'arsenicum-album',
    name: 'Arsenicum Album',
    scientificName: 'Arsénicum album',
    category: 'homeopatia',
    origin: {
      type: 'mineral',
      description: 'Trióxido de arsénico (As2O3). Muy tóxico en estado bruto.',
    },
    description: 'Remedio para ansiedad, inseguridad, gastroenteritis y problemas respiratorios.',
    mechanism: 'Modula el sistema nervioso y gastrointestinal. Regula la ansiedad y el miedo.',
    indications: ['Gastroenteritis aguda', 'Intoxicación alimentaria', 'Asma алергическая', 'Ansiedad con intranquilidad', 'Insomnio de madrugada', 'Eccema con sequedad', 'Pie diabético'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Precaución con tratamientos convencionales'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 2-3 veces al día.',
    synonyms: ['arsenicum', 'arsénico blanco', 'arsenic album', 'white arsenic'],
    warnings: ['TÓXICO en estado bruto', 'Solo diluciones homeopáticas'],
  },
  'baryta-carbonica': {
    id: 'baryta-carbonica',
    name: 'Baryta Carbonica',
    scientificName: 'Carbonato de bario',
    category: 'homeopatia',
    origin: {
      type: 'mineral',
      description: 'Carbonato de bario. Mineral tóxico en estado bruto.',
    },
    description: 'Remedio constitucional para personas con retraso del desarrollo y personas mayores.',
    mechanism: 'Modula el crecimiento y desarrollo. Actúa sobre sistema endocrino.',
    indications: ['Retraso del crecimiento en niños', 'Amígdalas hipertrofiadas', 'Enuresis nocturna', 'Arteriosclerosis', 'Demencia senil', 'Temblor senil', 'Hipertensión arterial'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 1-2 veces al día.',
    synonyms: ['baryta carb', 'carbonate of baryta', 'barium carbonicum'],
    warnings: ['TÓXICO en estado bruto'],
  },
  'belladonna': {
    id: 'belladonna',
    name: 'Belladonna',
    scientificName: 'Atropa belladonna',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Planta venenosa originaria de Europa. Muy tóxica en estado bruto.',
    },
    description: 'Remedio para procesos agudos con inicio súbito, calor, enrojecimiento y dolor pulsátil.',
    mechanism: 'Modula el sistema nervioso autónomo regulando la fiebre y la inflamación.',
    indications: ['Otitis media aguda', 'Amigdalitis aguda', 'Cefaleas pulsátiles', 'Fiebre alta de inicio súbito', 'Golpe de calor', 'Cistitis aguda', 'Abscesos'],
    contraindications: ['Glaucoma', 'Hipertrofia prostática', 'Obstrucción intestinal', 'Embarazo'],
    interactions: ['Potencia efectos de anticolinérgicos', 'Interacciona con antihistamínicos'],
    dosage: 'CH 5 a CH 15: 3-5 gránulos cada 30 minutos a 2 horas según intensidad.',
    synonyms: ['belladonna', 'bella doncella', 'deadly nightshade', 'belladonna'],
    warnings: ['TÓXICO en estado bruto', 'Solo usar en diluciones homeopáticas'],
  },
  'calcarea-carbonica': {
    id: 'calcarea-carbonica',
    name: 'Calcarea Carbonica',
    scientificName: 'Carbonato de calcio de ostra',
    category: 'homeopatia',
    origin: {
      type: 'mineral',
      description: 'Carbonato de calcio de ostra (Calcarea ostrearum).',
    },
    description: 'Remedio constitucional para niños regordetes, fríos y sudorosos.',
    mechanism: 'Modula el metabolismo del calcio y el crecimiento óseo.',
    indications: ['Retraso del cierre de fontanelas', 'Sudoración nocturna', 'Otitis de repetición', 'Amígdalas hypertrofiadas', 'Obesidad', 'Estrés', 'Ansiedad en niños'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 1-2 veces al día.',
    synonyms: ['calcarea carb', 'calcarea ostrearum', 'calcium carbonate', 'ostron shell'],
    warnings: ['Remedio constitucional de acción lenta'],
  },
  'calendula': {
    id: 'calendula',
    name: 'Caléndula',
    scientificName: 'Calendula officinalis',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Flor de la familia Asteraceae. Nativa de Europa.',
    },
    description: 'Remedio cicatrizante y antiinflamatorio. Excelente para heridas y quemaduras.',
    mechanism: 'Los triterpenoides reducen inflamación. Favorece granulación y эпителизацию.',
    indications: ['Heridas quirúrgicas', 'Queimaduras leves', 'Dermatitis del pañal', 'Gingivitis', 'Úlceras bucales', 'Fisuras anales', 'Eritema solar'],
    contraindications: ['Hipersensibilidad a Asteraceae'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6: 3-5 gránulos, 2-3 veces al día. Tópico: pomada o crema.',
    synonyms: ['calendula officinalis', 'maravilla', 'flor de morto'],
    warnings: ['Uso tópico principalmente', 'Infusión: no tragar'],
  },
  'chamomilla': {
    id: 'chamomilla',
    name: 'Chamomilla',
    scientificName: 'Matricaria chamomilla',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Manzanilla común. Familia Asteraceae.',
    },
    description: 'Remedio para niños irritables, dolor e insomnio. Gran успокоит.',
    mechanism: 'Modula el sistema nervioso y reduce la irritabilidad.',
    indications: ['Dolor de dentición', 'Cólicos del lactante', 'Irritabilidad extrema', 'Otitis media', 'Insomnio', 'Diarrea con cólicos', 'Asma con tos'],
    contraindications: ['Hipersensibilidad a Asteraceae'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, cada 15-30 min en crisis.',
    synonyms: ['chamomilla', 'manzanilla', 'camomila', 'chamomile'],
    warnings: ['No dar junto con Nux Vomica'],
  },
  'china': {
    id: 'china',
    name: 'China (Canela de China)',
    scientificName: 'Cinchona officinalis',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Corteza del árbol nativo de América del Sur. Fuente original de quinina.',
    },
    description: 'Remedio para debilidad, fatiga y problemas digestivos con pérdida de fluidos.',
    mechanism: 'En homeopatía: estimula la capacidad vital del organismo.',
    indications: ['Fatiga y debilidad general', 'Pérdida de fluidos corporales', 'Distensión abdominal con gases', 'Calambres musculares', 'Anemia', 'Deshidratación'],
    contraindications: ['Hipersensibilidad a la quinina', 'Embarazo (precaución)', 'G6PD deficiencia'],
    interactions: ['Warfarina (puede aumentar riesgo de sangrado)', 'Antiarrítmicos'],
    dosage: 'CH 5 a CH 15: 3-5 gránulos, 2-3 veces al día.',
    synonyms: ['china rubra', 'quina', 'corteza de china', 'cinchona', 'peruvian bark'],
    warnings: ['Contiene quinina natural', 'Consultar con médico si toma anticoagulantes'],
  },
  'colocynthis': {
    id: 'colocynthis',
    name: 'Colocynthis',
    scientificName: 'Citrullus colocynthis',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Planta de la familia Cucurbitaceae. El fruto es muy purgante.',
    },
    description: 'Remedio para cólicos intensos con mejora al doblarse.',
    mechanism: 'Modula la contractilidad del músculo liso intestinal.',
    indications: ['Cólicos abdominales', 'Cólicos renales', 'Cólicos hepáticos', 'Ciática izquierda', 'Neuralgia del trigémino', 'Dolor que mejora flexionándose'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos cada 15-30 min en crisis.',
    synonyms: ['colocynthis', 'coloquíntida', 'bitter apple', 'citrullus colocynthis'],
    warnings: ['Fruto muy purgante en estado bruto'],
  },
  'crotalus': {
    id: 'crotalus',
    name: 'Crotalus Horridus',
    scientificName: 'Crotalus horridus',
    category: 'homeopatia',
    origin: {
      type: 'animal',
      description: 'Veneno de serpiente cascabel. Very tóxica.',
    },
    description: 'Remedio para estados sépticos, hemólisis y fiebre continua.',
    mechanism: 'Modula la respuesta inflamatoria sistémica y la coagulación.',
    indications: ['Sepsis', 'Fiebre continua', 'Gangrena', 'Ernt bloody expectoration', 'Envenenamiento', 'Intoxicación alimentaria grave'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Precaución con anticoagulantes'],
    dosage: 'CH 200 a CH 1M: dosis única o semanal.',
    synonyms: ['crotalus', 'serpent', 'rattlesnake', 'crotalus hor'],
    warnings: ['Uso por profesionales únicamente'],
  },
  'dulcamara': {
    id: 'dulcamara',
    name: 'Dulcamara',
    scientificName: 'Solanum dulcamara',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Dulcamara o amargoso. Familia Solanaceae.',
    },
    description: 'Remedio para problemas que empeoran con frío y humedad.',
    mechanism: 'Modula la respuesta a cambios de temperatura y humedad.',
    indications: ['Resfriado con mucosidad', 'Bronquitis de frío', 'Cistitis de frío', 'Eccema por humedad', 'Artrosis que empeora con lluvia', 'Sinusitis', 'Otitis'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 2-3 veces al día.',
    synonyms: ['dulcamara', 'bittersweet', 'solanum dulcamara', 'woody nightshade'],
    warnings: ['Tóxico en estado bruto'],
  },
  'echinacea': {
    id: 'echinacea',
    name: 'Echinacea',
    scientificName: 'Echinacea purpurea',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Equinácea. Planta de la familia Asteraceae de América del Norte.',
    },
    description: 'Remedio para prevenir y tratar infecciones. Inmunomodulador.',
    mechanism: 'Estimula el sistema inmune inespecífico. Activa macrófagos y células NK.',
    indications: ['Prevención de infecciones', 'Resfriados de repetición', 'Gripe', 'Infecciones cutáneas', 'Abscesos', 'Furunculosis', 'Sepsis leve'],
    contraindications: ['Enfermedades autoinmunes', 'VIH/SIDA', 'Embarazo', 'Lactancia'],
    interactions: ['Inmunosupresores', 'Corticoides'],
    dosage: 'CH 6 a CH 30: 3-5 gránulos, 2-3 veces al día.',
    synonyms: ['echinacea purpurea', 'equinácea', 'purple coneflower'],
    warnings: ['No usar continuamente más de 8 semanas'],
  },
  'gelsemium': {
    id: 'gelsemium',
    name: 'Gelsemium',
    scientificName: 'Gelsemium sempervirens',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Gelsemio o jazmín de Carolina. Muy tóxica.',
    },
    description: 'Remedio para debilidad, temblores y fiebre con escalofríos.',
    mechanism: 'Modula el sistema nervioso y la respuesta muscular.',
    indications: ['Gripe con postración', 'Migraña con temblores', 'Ansiedad ante exámenes', 'Parálisis facial', 'Temblores esenciales', 'Fiebre con escalofríos', 'Astenozoospermia'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Precaución con antihipertensivos'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 2-4 veces al día.',
    synonyms: ['gelsemium', 'gelsemio', 'yellow jasmine', 'carolina jasmine'],
    warnings: ['TÓXICO en estado bruto', 'Solo diluciones homeopáticas'],
  },
  'graphites': {
    id: 'graphites',
    name: 'Graphites',
    scientificName: 'Grafito',
    category: 'homeopatia',
    origin: {
      type: 'mineral',
      description: 'Grafito natural. Forma alotrópica del carbono.',
    },
    description: 'Remedio para eccema con liquenificación y problemas digestivos.',
    mechanism: 'Modula la respuesta inflamatoria crónica de la piel.',
    indications: ['Eccema con liquenificación', 'Dermatitis atópica', 'Heridas que no cicatrizan', 'Estreñimiento', 'Obesidad', 'Trastornos menstruales', 'Otitis crónica'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 1-2 veces al día.',
    synonyms: ['graphites', 'grafito', 'black lead', 'plumbago'],
    warnings: ['Remedio constitucional de acción lenta'],
  },
  'hamamelis': {
    id: 'hamamelis',
    name: 'Hamamelis Virginiana',
    scientificName: 'Hamamelis virginiana',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Avellano de bruja. Arbusto de América del Norte.',
    },
    description: 'Remedio para problemas venosos con sensación de contusión.',
    mechanism: 'Los taninos y flavonoides reducen permeabilidad capilar.',
    indications: ['Hemorroides con dolor', 'Varices', 'Piernas pesadas', 'Hematomas', 'Hemorragias nasales', 'Varicocele', 'Flebítis superficial'],
    contraindications: ['Hipersensibilidad'],
    interactions: ['Potencia anticoagulantes'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 2-3 veces al día.',
    synonyms: ['hamamelis', 'witch hazel', 'avellano de bruja'],
    warnings: ['No aplicar sobre heridas abiertas'],
  },
  'hepatic': {
    id: 'hepatic',
    name: 'Hepar Sulfuris',
    scientificName: 'Hepar sulfuris calcareum',
    category: 'homeopatia',
    origin: {
      type: 'mineral',
      description: 'Mezcla de calcio e azufre. Olor a huevo podrido.',
    },
    description: 'Remedio para procesos supurativos con hipersensibilidad al frío.',
    mechanism: 'Modula la respuesta inmune y la supuración.',
    indications: ['Abscesos', 'Furunculosis', 'Otitis supurada', 'Sinusitis purulenta', 'Amigdalitis con pus', 'Tos con expectoración purulenta', 'Dermatitis supurada'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 2-3 veces al día.',
    synonyms: ['hepatic', 'heppar sulfur', 'hepar sulph', 'hepar sulf'],
    warnings: ['Olor desagradable', 'Remedio para fases avanzadas'],
  },
  'hyoscyamus': {
    id: 'hyoscyamus',
    name: 'Hyoscyamus',
    scientificName: 'Hyoscyamus niger',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Hierba topera o beleño negro. Muy tóxica.',
    },
    description: 'Remedio para tics, sacudidas musculares y delirio.',
    mechanism: 'Modula el sistema nervioso extrapiramidal.',
    indications: ['Tics nerviosos', 'Coroa', 'Delirio con excitación', 'Insomnio con hablar dormido', 'Parkinson', 'Epilepsia', 'Histeria'],
    contraindications: ['Glaucoma', 'Hipertrofia prostática', 'Arritmias'],
    interactions: ['Anticolinérgicos', 'Antidepresivos tricíclicos'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 2-3 veces al día.',
    synonyms: ['hyoscyamus', 'beleño negro', 'henbane', 'hyoscyamus niger'],
    warnings: ['TÓXICO en estado bruto'],
  },
  'ignatia': {
    id: 'ignatia',
    name: 'Ignatia Amara',
    scientificName: 'Ignatia amara',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Haba de San Ignacio. Semilla Strychnos ignatii.',
    },
    description: 'Remedio para duelo, tristeza y problemas emocionales.',
    mechanism: 'Modula el sistema nervioso en respuestas emocionales.',
    indications: ['Duelo y tristeza', 'Lamento', 'Depresión reactiva', 'Insomnio por preocupaciones', 'Espasmos emocionales', 'Globus hisser', 'Estreñimiento emocional'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 1-3 veces al día.',
    synonyms: ['ignatia', 'ignatia amara', 'St. Ignatius bean', 'faba ignatii'],
    warnings: ['Remedio emocional - efecto sutil'],
  },
  'iris-versicolor': {
    id: 'iris-versicolor',
    name: 'Iris Versicolor',
    scientificName: 'Iris versicolor',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Lirio azul americano. Planta acuática de América del Norte.',
    },
    description: 'Remedio para migrañas, problemas digestivos y hormonal.',
    mechanism: 'Actúa sobre el sistema nervioso y glandular. Regula metabolismo.',
    indications: ['Migrañas izquierda', 'Problemas digestivos crónicos', 'Desórdenes hormonales', 'Pancreatitis', 'Gastritis crónica', 'Acidez de repetición'],
    contraindications: ['Hipersensibilidad a Iris'],
    interactions: ['Sin interacciones conocidas'],
    dosage: 'CH 5 a CH 15: 3-5 gránulos, 2-3 veces al día.',
    synonyms: ['iris', 'blue flag', 'lirio azul'],
    warnings: ['No confundir con Iris germanica'],
  },
  'kali-bichromicum': {
    id: 'kali-bichromicum',
    name: 'Kali Bichromicum',
    scientificName: 'Bicromato de potasio',
    category: 'homeopatia',
    origin: {
      type: 'mineral',
      description: 'Bicromato de potasio. Sal tóxica de cromo.',
    },
    description: 'Remedio para secreciones densas, pegajosas y amarillas.',
    mechanism: 'Modula la mucosidad y las secreciones del tracto respiratorio y digestivo.',
    indications: ['Sinusitis con moco espeso', 'Bronquitis crónica', 'Rinitis', 'Úlcera gástrica', 'Cefalea sinusal', 'Acné quístico'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 2-3 veces al día.',
    synonyms: ['kali bichromicum', 'potassium dichromate', 'bicromato de potasio'],
    warnings: ['Tóxico en estado bruto'],
  },
  'kali-carbonicum': {
    id: 'kali-carbonicum',
    name: 'Kali Carbonicum',
    scientificName: 'Carbonato de potasio',
    category: 'homeopatia',
    origin: {
      type: 'mineral',
      description: 'Carbonato de potasio. Sal mineral esencial.',
    },
    description: 'Remedio para debilidad de espalda, edema y problemas respiratorios.',
    mechanism: 'Modula el metabolismo y la función cardíaca.',
    indications: ['Dolor de espalda baja', 'Edema maleolar', 'Asma cardíaca', 'Estreñimiento', 'Cistitis', 'Menopausia con sofocos', 'Arritmias'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Precaución con digitálicos'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 1-2 veces al día.',
    synonyms: ['kali carb', 'potassium carbonate', 'carbonate of potash'],
    warnings: ['Remedio constitucional'],
  },
  'lachesis': {
    id: 'lachesis',
    name: 'Lachesis Mutus',
    scientificName: 'Lachesis muta',
    category: 'homeopatia',
    origin: {
      type: 'animal',
      description: 'Veneno de serpiente surucucú. Muy tóxica.',
    },
    description: 'Remedio para problemas circulatorios, menopausia y celulitis.',
    mechanism: 'Modula la circulación sanguínea y el sistema nervioso.',
    indications: ['Menopausia con sofocos', 'Cefalea menopáusica', 'Celulitis', 'Varices', 'Flebítis', 'Angina de pecho', 'Palpitaciones'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Precaución con anticoagulantes'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 1-2 veces al día.',
    synonyms: ['lachesis', 'lachesis muta', 'surucucu', 'bushmaster'],
    warnings: ['Tóxico en estado bruto'],
  },
  'lycopodium': {
    id: 'lycopodium',
    name: 'Lycopodium Clavatum',
    scientificName: 'Lycopodium clavatum',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Licopodio o musgo de club. Helecho primitivo.',
    },
    description: 'Remedio constitucional para problemas digestivos y urinarios.',
    mechanism: 'Modula la función digestiva y hepática.',
    indications: ['Flatulencia', 'Distensión abdominal', 'Estreñimiento', 'Cálculos renales', 'Cistitis de repetición', 'Impotencia', 'Calvicie'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 1-2 veces al día.',
    synonyms: ['lycopodium', 'licopodio', 'club moss', 'wolf\'s claw'],
    warnings: ['Remedio constitucional de acción profunda'],
  },
  'magnesia-phosphorica': {
    id: 'magnesia-phosphorica',
    name: 'Magnesia Phosphorica',
    scientificName: 'Fosfato de magnesio',
    category: 'homeopatia',
    origin: {
      type: 'mineral',
      description: 'Fosfato de magnesio. Sal mineral.',
    },
    description: 'Remedio para cólicos y espasmos musculares.',
    mechanism: 'Relaja el músculo liso y estriado.',
    indications: ['Cólicos abdominales', 'Cólicos menstruales', 'Espasmos musculares', 'Calambres', 'Tics nerviosos', 'Neuralgia', 'Asma espasmódica'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, cada 15-30 min en crisis.',
    synonyms: ['magnesia phos', 'phosphate of magnesia', 'fosfato de magnesio'],
    warnings: ['Disolver en agua para mejor absorción'],
  },
  'mercurius-solubilis': {
    id: 'mercurius-solubilis',
    name: 'Mercurius Solubilis',
    scientificName: 'Mercurius solubilis Hahnemanni',
    category: 'homeopatia',
    origin: {
      type: 'mineral',
      description: 'Mercurio amalgamado con grafito y lactosa.',
    },
    description: 'Remedio para inflamaciones con secreciones y mal aliento.',
    mechanism: 'Modula la respuesta inflamatoria con supuración.',
    indications: ['Amigdalitis con pus', 'Gingivitis', 'Estomatitis', 'Otitis supurada', 'Bronquitis crónica', 'Diarrea con urgencia', 'Cistitis'],
    contraindications: ['Hipersensibilidad al mercurio', 'Enfermedad renal'],
    interactions: ['Precaución con sales de mercurio convencionales'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 2-3 veces al día.',
    synonyms: ['mercurius sol', 'mercurio soluble', 'quicksilver', 'hydrargyrum'],
    warnings: ['Remedio para casos avanzados'],
  },
  'natrum-muriaticum': {
    id: 'natrum-muriaticum',
    name: 'Natrum Muriaticum',
    scientificName: 'Cloruro de sodio',
    category: 'homeopatia',
    origin: {
      type: 'mineral',
      description: 'Cloruro de sodio (sal marina). Elemento esencial.',
    },
    description: 'Remedio constitucional para migrañas, anemia y封闭情感.',
    mechanism: 'Regula el balance hídrico celular y la emociones.',
    indications: ['Migrañas', 'Anemia', 'Estreñimiento', 'Resfriados frecuentes', 'Alergias', 'Depresión', 'Resaca'],
    contraindications: ['Hipertensión severa'],
    interactions: ['Precaución con litio'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 2-3 veces al día.',
    synonyms: ['natrum mur', 'natrum muriaticum', 'sal marina', 'sodium chloride', 'sea salt'],
    warnings: ['No tomar con café o menta'],
  },
  'natrum-sulfuricum': {
    id: 'natrum-sulfuricum',
    name: 'Natrum Sulfuricum',
    scientificName: 'Sulfato de sodio',
    category: 'homeopatia',
    origin: {
      type: 'mineral',
      description: 'Sulfato de sodio (sal de Glauber).',
    },
    description: 'Remedio para problemas hepáticos y ciática.',
    mechanism: 'Modula la función hepática y el drenaje.',
    indications: ['Ictericia', 'Hepatitis', 'Cálculos biliares', 'Ciática derecha', 'Gota', 'Asma hepática', 'Depresión'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 1-2 veces al día.',
    synonyms: ['natrum sulf', 'sodium sulfate', 'sulfato de sodio', 'glauber salts'],
    warnings: ['Remedio hepático'],
  },
  'nux-vomica': {
    id: 'nux-vomica',
    name: 'Nux Vomica',
    scientificName: 'Strychnos nux-vomica',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Árbol de India y sudeste asiático. Semillas contienen estricnina.',
    },
    description: 'Remedio para síntomas digestivos por excesos.',
    mechanism: 'Regula el sistema nervioso entérico y el eje estrés-digestión.',
    indications: ['Estreñimiento con esfuerzo', 'Náuseas matutinas', 'Reflujo por estrés', 'Resaca', 'Indigestión por excesos', 'Insomnio de madrugada', 'Hemorroides'],
    contraindications: ['Embarazo (consultar médico)', 'Enfermedades hepáticas graves', 'Úlcera péptica activa'],
    interactions: ['Potencia estimulantes del sistema nervioso', 'Precaución con antidepresivos'],
    dosage: 'CH 5 a CH 15: 3-5 gránulos, 15 minutos antes de comidas.',
    synonyms: ['nux vomica', 'nux-vomica', 'vómito de nuez', 'strychnine tree', 'nux vom'],
    warnings: ['Contiene estricnina en estado bruto', 'Dilución homeopática segura'],
  },
  'phellandrium': {
    id: 'phellandrium',
    name: 'Phellandrium',
    scientificName: 'Phellandrium aquaticum',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Planta acuática de Europa.',
    },
    description: 'Remedio para problemas pulmonares con expectoración.',
    mechanism: 'Modula la función respiratoria y la eliminación de mucosidad.',
    indications: ['Bronquiectasias', 'Tos con expectoración fétida', 'Tuberculosis pulmonar', 'Absceso pulmonar', 'Empiema'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 2-3 veces al día.',
    synonyms: ['phellandrium', 'finlandria', 'water fennel'],
    warnings: ['Remedio para casos crónicos respiratorios'],
  },
  'phosphorus': {
    id: 'phosphorus',
    name: 'Phosphorus',
    scientificName: 'Fósforo',
    category: 'homeopatia',
    origin: {
      type: 'mineral',
      description: 'Elemento químico esencial. No es el fósforo radioactivo.',
    },
    description: 'Remedio para hemorragias, ansiedad y problemas respiratorios.',
    mechanism: 'Modula permeabilidad vascular. Actúa sobre SNC y sistema respiratorio.',
    indications: ['Hemorragias (epistaxis)', 'Bronquitis', 'Neumonía', 'Ansiedad anticipatoria', 'Angustia', 'Hepatitis', 'Fiebre hemorrágica'],
    contraindications: ['Enfermedad ósea activa', 'Insuficiencia renal'],
    interactions: ['Potencia heparina', 'Precaución con digitálicos'],
    dosage: 'CH 5 a CH 15: 3-5 gránulos, 2-4 veces al día.',
    synonyms: ['fosforo', 'phosphorus', 'p', 'phosphoricum'],
    warnings: ['No confundir con fósforo blanco (tóxico)'],
  },
  'phytolacca': {
    id: 'phytolacca',
    name: 'Phytolacca Decandra',
    scientificName: 'Phytolacca decandra',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Fitolaa o carmine. Planta tóxica de América.',
    },
    description: 'Remedio para problemas mamarios y glandulares.',
    mechanism: 'Modula la función glandular y mamaria.',
    indications: ['Mastitis', 'Ginecomastia', 'Dolor mamario', 'Amigdalitis', 'Faringitis', 'Induración mamaria', 'Secreciones mamarias'],
    contraindications: ['Embarazo'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 2-3 veces al día.',
    synonyms: ['phytolacca', 'phytolacca decandra', 'pokeweed', 'carmin'],
    warnings: ['Tóxica en estado bruto'],
  },
  'platina': {
    id: 'platina',
    name: 'Platina',
    scientificName: 'Platino metálico',
    category: 'homeopatia',
    origin: {
      type: 'mineral',
      description: 'Metal platino. Elemento noble.',
    },
    description: 'Remedio para síntomas que empeoran con consuelo.',
    mechanism: 'Modula la sensibilidad nerviosa y la rigidez muscular.',
    indications: ['Neuralgia pudenda', 'Vaginismo', 'Ansiedad con necesidad de cariño', 'Hipocondría', 'Constipación', 'Impotencia', 'Temblor'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 1-2 veces al día.',
    synonyms: ['platina', 'platinum', 'platino'],
    warnings: ['Remedio constitucional'],
  },
  'pulsatilla': {
    id: 'pulsatilla',
    name: 'Pulsatilla',
    scientificName: 'Anemone pulsatilla',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Flor de pascua. Planta de la familia Ranunculaceae.',
    },
    description: 'Remedio para personas tiernas, lloronas y que mejoran con aire fresco.',
    mechanism: 'Modula las secreciones y la temperatura corporal.',
    indications: ['Otitis media', 'Conjuntivitis', 'Resfriados', 'Cistitis', 'Amigdalitis', 'Varicela', 'Rubéola', 'Menopausia'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 2-3 veces al día.',
    synonyms: ['pulsatilla', 'pasque flower', 'wind flower', 'anemone'],
    warnings: ['Personas frioleras o que empeoran con frío'],
  },
  'rhododendron': {
    id: 'rhododendron',
    name: 'Rhododendron',
    scientificName: 'Rhododendron chrysanthum',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Rododendro. Planta de montaña tóxica.',
    },
    description: 'Remedio para problemas que empeoran antes de tormentas.',
    mechanism: 'Modula la respuesta a cambios atmosféricos.',
    indications: ['Cefalea que precede tormentas', 'Reumatismo que empeora con lluvia', 'Sinusitis frontal', 'Orchitis', 'Cistitis', 'Neuralgia del trigémino'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 1-2 veces al día.',
    synonyms: ['rhododendron', 'rhododendron chrysanthum', 'snow rose'],
    warnings: ['Tóxico en estado bruto'],
  },
  'rhus-toxicodendron': {
    id: 'rhus-toxicodendron',
    name: 'Rhus Toxicodendron',
    scientificName: 'Rhus toxicodendron',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Hiedra venenosa. Muy tóxica por contacto.',
    },
    description: 'Remedio para rigidez que mejora con movimiento.',
    mechanism: 'Modula la respuesta inflamatoria articular.',
    indications: ['Artritis con rigidez matutina', 'Esguinces', 'Lumbago', 'Ciática', 'Herpes zóster', 'Eccema vesicular', 'Fiebre reumática'],
    contraindications: ['Hipersensibilidad a la planta'],
    interactions: ['No dar junto con Apis'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 2-4 veces al día.',
    synonyms: ['rhus tox', 'rhus toxicodendron', 'poison ivy', 'hiedra venenosa'],
    warnings: ['TÓXICO por contacto en estado bruto', 'Dilución homeopática segura'],
  },
  'sepia': {
    id: 'sepia',
    name: 'Sepia',
    scientificName: 'Sepia officinalis',
    category: 'homeopatia',
    origin: {
      type: 'animal',
      description: 'Tinta de calamar o jibia. Molusco marino.',
    },
    description: 'Remedio para agotamiento, desórdenes hormonales y uterinos.',
    mechanism: 'Modula eje hipotálamo-hipófisis-gonadal.',
    indications: ['Menopausia', 'Sofocos', 'Desórdenes menstruales', 'Astenia', 'Prolapso uterino', 'Estreñimiento', 'Cistitis', 'Depresión'],
    contraindications: ['Embarazo (solo bajo supervisión)', 'Lactancia'],
    interactions: ['Potencia tratamientos hormonales'],
    dosage: 'CH 5 a CH 15: 3-5 gránulos, 1-2 veces al día.',
    synonyms: ['sepia', 'sepia officinalis', 'tinta de calamar', 'cuttlefish'],
    warnings: ['No usar con Antimonium crudum simultáneamente'],
  },
  'silicea': {
    id: 'silicea',
    name: 'Silicea',
    scientificName: 'Dióxido de silicio',
    category: 'homeopatia',
    origin: {
      type: 'mineral',
      description: 'Sílice o cuarzo.甚常温.',
    },
    description: 'Remedio para problemas supurativos crónicos y debilidad.',
    mechanism: 'Modula la eliminación de pus y la síntesis de colágeno.',
    indications: ['Abscesos crónicos', 'Furunculosis de repetición', 'Fístulas', 'Retraso de consolidación ósea', 'Infecciones respiratorias crónicas', 'Unidades débiles'],
    contraindications: ['Implantes metálicos', 'Embarazo (precaución)'],
    interactions: ['Precaución con tratamientos quelantes'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 1-2 veces al día.',
    synonyms: ['silicea', 'sílice', 'silica', 'quartz', 'flint'],
    warnings: ['Remedio de acción profunda y lenta'],
  },
  'stramonium': {
    id: 'stramonium',
    name: 'Stramonium',
    scientificName: 'Datura stramonium',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Estramonio o老汉翁. Muy tóxica.',
    },
    description: 'Remedio para estados de agitación, miedo y convulsiones.',
    mechanism: 'Modula el sistema nervioso central y autónomo.',
    indications: ['Agitación psicomotora', 'Delirio', 'Epilepsia', 'Parkinson', 'Asma con tos ferina', 'Miedo a la oscuridad', 'Pesadillas'],
    contraindications: ['Glaucoma', 'Hipertrofia prostática', 'Arritmias'],
    interactions: ['Anticolinérgicos', 'Sedantes'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 2-3 veces al día.',
    synonyms: ['stramonium', 'estramonio', 'jimson weed', 'thorn apple', 'datura'],
    warnings: ['TÓXICO en estado bruto'],
  },
  'sulfur': {
    id: 'sulfur',
    name: 'Sulfur',
    scientificName: 'Azufre',
    category: 'homeopatia',
    origin: {
      type: 'mineral',
      description: 'Elemento químico natural. Presente en aminochácidos y vitaminas del grupo B.',
    },
    description: 'Remedio constitucional para problemas cutáneos y digestivos.',
    mechanism: 'Modula la respuesta inflamatoria crónica.',
    indications: ['Eccema', 'Dermatitis', 'Psoriasis', 'Acné', 'Estreñimiento crónico', 'Hemorroides', 'Enuresis nocturna', 'Artritis gotosa'],
    contraindications: ['No usar en fase aguda grave'],
    interactions: ['No dar después de Apis o Rhus-toxicodendron'],
    dosage: 'CH 5 a CH 15: 3-5 gránulos, 1-2 veces al día. Mejor en ayunas.',
    synonyms: ['azufre', 'sulf', 'sulfur', 'sulphur', 'sulph'],
    warnings: ['Remedio profundo - efecto duradero', 'Primeros empeoramientos posibles'],
  },
  'symphytum': {
    id: 'symphytum',
    name: 'Symphytum',
    scientificName: 'Symphytum officinale',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Consuelda mayor. Planta de Europa.',
    },
    description: 'Remedio para consolidación de fracturas y heridas.',
    mechanism: 'Favorece la formación de callo óseo y tejidos.',
    indications: ['Fracturas', 'Traumatismos óseos', 'Heridas penetrantes', 'Úlceras', 'Fístulas', 'Periostitis'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 2-3 veces al día.',
    synonyms: ['symphytum', 'consuelda mayor', 'comfrey', 'boneset'],
    warnings: ['NO usar internamente por tiempo prolongado'],
  },
  'thuja': {
    id: 'thuja',
    name: 'Thuja Occidentalis',
    scientificName: 'Thuja occidentalis',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Árbol de la vida. Familia Cupressaceae.',
    },
    description: 'Remedio para verrugas, efectos secundarios de vacunas.',
    mechanism: 'Modula el crecimiento celular y la respuesta inmune.',
    indications: ['Verrugas', 'Papilomas', 'Efectos de vacunas', 'Cistitis crónica', 'Prostatitis', 'Diarrea crónica', 'Psoriasis ungueal'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 1-2 veces al día.',
    synonyms: ['thuja', 'thuja occidentalis', 'arbol de la vida', 'white cedar'],
    warnings: ['Remedio antiviral'],
  },
  'veratrum-album': {
    id: 'veratrum-album',
    name: 'Veratrum Album',
    scientificName: 'Veratrum album',
    category: 'homeopatia',
    origin: {
      type: 'planta',
      description: 'Eléboro blanco. Muy tóxicos.',
    },
    description: 'Remedio para colapso con frío y diarrea profusa.',
    mechanism: 'Modula el sistema nervioso y la circulación.',
    indications: ['Cólera', 'Diarrea acuosa profusa', 'Colapso circulatorio', 'Deshidratación', 'Vómitos incoercibles', 'Hipoglucemia', 'Shock'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Precaución con digitálicos'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos cada 15-30 min en crisis.',
    synonyms: ['veratrum album', 'eléboro blanco', 'white hellebore'],
    warnings: ['TÓXICO en estado bruto'],
  },
  'zincum-metallicum': {
    id: 'zincum-metallicum',
    name: 'Zincum Metallicum',
    scientificName: 'Zinc metálico',
    category: 'homeopatia',
    origin: {
      type: 'mineral',
      description: 'Zinc metálico. Oligoelemento esencial.',
    },
    description: 'Remedio para debilidad nerviosa y síndrome de piernas inquietas.',
    mechanism: 'Modula la transmisión nerviosa y el sistema nervioso.',
    indications: ['Síndrome de piernas inquietas', 'Temblores', 'Epilepsia', 'Fatiga mental', 'Insomnio', 'Depresión', 'Neuralgia'],
    contraindications: ['Ninguna bajo supervisión médica'],
    interactions: ['Precaución con quelantes'],
    dosage: 'CH 6 a CH 15: 3-5 gránulos, 1-2 veces al día.',
    synonyms: ['zincum met', 'zinc', 'zinc metallicum'],
    warnings: ['Remedio neurológico'],
  },
};

// Fitoterapia extendida
export const HERBAL_DATABASE: Record<string, ExtendedIngredientInfo> = {
  // Hierbas para el Sistema Digestivo
  'alcachofa': {
    id: 'alcachofa',
    name: 'Alcachofa',
    scientificName: 'Cynara scolymus',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta de la familia Asteraceae. Origen mediterráneo.',
    },
    description: 'Hepatoprotector y drenador hepático. Favorece la función biliar.',
    mechanism: 'La cinarina estimula la secreción biliar y protege hepatocitos.',
    indications: ['Dispepsia', 'Hígado perezoso', 'Colesterol alto', 'Digestión lenta', 'Náuseas', 'Hinchazón'],
    contraindications: ['Obstrucción biliar', 'Cálculos biliares grandes', 'Embarazo'],
    interactions: ['Precaución con anticoagulantes'],
    dosage: 'Extracto seco: 600-1200 mg/día en 2-3 dosis.',
    synonyms: ['alcachofa', 'alcaucil', ' Cynara scolymus', 'artichoke'],
    warnings: ['Boca amarga temporal', 'No usar en insuficiencia hepática grave'],
  },
  'cardo-mariano': {
    id: 'cardo-mariano',
    name: 'Cardo Mariano',
    scientificName: 'Silybum marianum',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta de la familia Asteraceae. Originaria del Mediterráneo.',
    },
    description: 'Potente hepatoprotector. Favorece la regeneración hepática.',
    mechanism: 'La silimarina protege membranas hepatocíticas y estimula síntesis proteica.',
    indications: ['Hepatitis', 'Cirrosis inicial', 'Protección hepática', 'Resaca', 'Envenenamiento', 'Colesterol'],
    contraindications: ['Embarazo', 'Lactancia', 'Alergia a Asteraceae'],
    interactions: ['Puede potenciar监护型药物'],
    dosage: 'Extracto 70-80% silimarina: 140-210 mg, 2-3 veces al día.',
    synonyms: ['cardo mariano', 'silybum', 'milk thistle', 'silimarina'],
    warnings: ['Efecto laxante leve posible', 'Calidad variable de extractos'],
  },
  'diente-de-leon': {
    id: 'diente-de-leon',
    name: 'Diente de León',
    scientificName: 'Taraxacum officinale',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta común de prados. Familia Asteraceae.',
    },
    description: 'Diurético y drenador hepatorenal. Rico en potasio.',
    mechanism: 'Los terpenoides y flavonoides tienen efecto diurético y colerético.',
    indications: ['Edema', 'Retención de líquidos', 'Hígado perezoso', 'Digestión lenta', 'Estreñimiento', 'Gota'],
    contraindications: ['Obstrucción biliar', 'Cálculos biliares'],
    interactions: ['Diuréticos (potencia efecto)', 'Litio'],
    dosage: 'Infusión: 2-4 g de raíz/día. Extracto: seguir indicaciones.',
    synonyms: ['diente de león', 'taraxacum', 'dandelion', 'panadero'],
    warnings: ['Piel sensible al látex', 'Puede aumentar necesidad de potasio'],
  },
  'gentiana': {
    id: 'gentiana',
    name: 'Genciana',
    scientificName: 'Gentiana lutea',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta de montaña. Raíz muy amarga.',
    },
    description: 'Amaro tónico. Estimula el apetito y la digestión.',
    mechanism: 'Los principios amargos estimulan receptores gustativos, aumentando secreciones digestivas.',
    indications: ['Dispepsia hiposecretora', 'Falta de apetito', 'Anemia', 'Convalecencia', 'Digestión lenta'],
    contraindications: ['Gastritis ácida', 'Úlcera péptica', 'Embarazo'],
    interactions: ['Antiácidos', 'Bloqueadores H2'],
    dosage: 'Tintura: 1-4 ml antes de comidas. Infusión: 1-2 g/día.',
    synonyms: ['gentiana', 'gentian', 'bitter root', 'gentiane'],
    warnings: ['No usar en hipertensión'],
  },
  'hinojo': {
    id: 'hinojo',
    name: 'Hinojo',
    scientificName: 'Foeniculum vulgare',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta umbelífera. Semillas y frutos.',
    },
    description: 'Carminativo y espasmolítico gastrointestinal.',
    mechanism: 'El anetol relaja músculo liso intestinal y reduce flatulencia.',
    indications: ['Cólicos', 'Flatulencia', 'Aerofagia', 'Digestión lenta', 'Lactancia (galactogogo)'],
    contraindications: ['Embarazo', 'Cáncer hormono-dependiente'],
    interactions: ['Precaución con estrógenos'],
    dosage: 'Infusión de semillas: 1-2 g después de comidas.',
    synonyms: ['hinojo', 'foeniculum', 'fennel', 'finocchio'],
    warnings: ['Dosis altas pueden causar convulsiones'],
  },
  'jenjibre': {
    id: 'jenjibre',
    name: 'Jenjibre',
    scientificName: 'Zingiber officinale',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Rizoma tropical. Usado hace más de 5000 años.',
    },
    description: 'Antiinflamatorio natural, antiemético y estimulante digestivo.',
    mechanism: 'Los gingeroles inhiben COX-1 y COX-2. Acción antiemética por bloqueo de receptores 5-HT3.',
    indications: ['Náuseas y vómitos', 'Dispepsia funcional', 'Dolor articular', 'Dolor muscular', 'Mejora circulación', 'Dolor de garganta'],
    contraindications: ['Cálculos biliares', 'Cirugía (suspender 2 semanas)', 'Embarazo (dosis altas)'],
    interactions: ['Potencia anticoagulantes', 'Puede reducir glucemia'],
    dosage: 'Raíz fresca: 1-2 g/día. Extracto: 250-500 mg 2-3 veces al día.',
    synonyms: ['jenjibre', 'jengibre', 'ginger', 'kion'],
    warnings: ['Dosis >2g puede causar reflujo', 'No masticar en ayunas'],
  },
  'manzanilla': {
    id: 'manzanilla',
    name: 'Manzanilla',
    scientificName: 'Matricaria chamomilla',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta medicinal clásica. Familia Asteraceae.',
    },
    description: 'Antiinflamatoria, ansiolítica y digestiva.',
    mechanism: 'Los flavonoides y cumarinas tienen efecto antiinflamatorio y ansiolítico.',
    indications: ['Ansiedad leve', 'Insomnio', 'Cólicos', 'Gastritis', 'Eccema', 'Conjuntivitis', 'Heridas'],
    contraindications: ['Alergia a Asteraceae', 'Embarazo'],
    interactions: ['Sedantes', 'Anticoagulantes'],
    dosage: 'Infusión: 2-3 g de flores, 3-4 veces al día.',
    synonyms: ['manzanilla', 'chamomile', 'camomila', 'matricaria'],
    warnings: ['Puede causar reacciones alérgicas'],
  },
  'melisa': {
    id: 'melisa',
    name: 'Melisa',
    scientificName: 'Melissa officinalis',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Toronjil o citronela. Planta mediterránea.',
    },
    description: 'Ansiolítica suave, sedante y antiviral.',
    mechanism: 'Los terpenos modulan receptores GABA. El ácido rosmarínico tiene efecto antiviral.',
    indications: ['Ansiedad', 'Insomnio', 'Nerviosismo', 'Herpes labial', 'Palpitaciones', 'Digestión nerviosa'],
    contraindications: ['Hipotiroidismo', 'Glaucoma'],
    interactions: ['Sedantes', 'Hormonas tiroideas'],
    dosage: 'Infusión: 1.5-4.5 g/día. Extracto: seguir indicaciones.',
    synonyms: ['melisa', 'melissa', 'lemon balm', 'toronjil'],
    warnings: ['Efecto hipotiroideo', 'Puede interactuar con sedantes'],
  },
  'menta-piperita': {
    id: 'menta-piperita',
    name: 'Menta Piperita',
    scientificName: 'Mentha × piperita',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Híbrido de menta. Planta aromática.',
    },
    description: 'Carminativo, antiemético y refrescante.',
    mechanism: 'El mentol relaja músculo liso y tiene efecto refrescante.',
    indications: ['Náuseas', 'Cólicos', 'Flatulencia', 'Síndrome del intestino irritable', 'Cefalea tensional', 'Congestión nasal'],
    contraindications: ['ERGE severa', 'Cálculos biliares', 'Niños <2 años'],
    interactions: ['Antiácidos', 'Bloqueadores de calcio'],
    dosage: 'Infusión: 1-2 g de hojas, después de comidas.',
    synonyms: ['menta', 'peppermint', 'menta piperita'],
    warnings: ['Puede empeorar reflujo', 'No usar aceites esenciales puros internamente'],
  },
  'regaliz': {
    id: 'regaliz',
    name: 'Regaliz',
    scientificName: 'Glycyrrhiza glabra',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta leguminosa. Raíz muy dulce.',
    },
    description: 'Antiinflamatorio, expectorante y protector gástrico.',
    mechanism: 'La glicirricina tiene efecto antiinflamatorio y pseudoaldosterona-like.',
    indications: ['Gastritis', 'Úlcera gástrica', 'Tos seca', 'Faringitis', 'Estreñimiento', 'Fatiga adrenal'],
    contraindications: ['Hipertensión', 'Insuficiencia cardíaca', 'Embarazo', 'Cirrosis'],
    interactions: ['Diuréticos', 'Digoxina', 'Corticoides', 'Antihipertensivos'],
    dosage: 'Decocción: 1-5 g/día. Extracto: seguir indicaciones.',
    synonyms: ['regaliz', 'licorice', 'glycyrrhiza', 'palodul'],
    warnings: ['Uso prolongado causa retención de líquidos e hipertensión', 'No exceder 4-6 semanas'],
  },
  'valeriana': {
    id: 'valeriana',
    name: 'Valeriana',
    scientificName: 'Valeriana officinalis',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta herbácea de Europa. Usada como sedante desde la antigüedad romana.',
    },
    description: 'Sedante natural para insomnio y ansiedad.',
    mechanism: 'Los ácidos valerenicos potencian receptores GABA-A.',
    indications: ['Insomnio', 'Ansiedad leve a moderada', 'Nerviosismo', 'Calambres musculares nocturnos', 'Tensión muscular por estrés'],
    contraindications: ['Embarazo (1er trimestre)', 'Lactancia', 'Hepatopatías severas'],
    interactions: ['Potencia benzodiacepinas', 'Potencia barbitúricos', 'Alcohol'],
    dosage: 'Extracto (0.8% ácidos valerenicos): 400-900 mg antes de acostarse.',
    synonyms: ['valeriana', 'valerian root', 'hierba de los gatos', 'all-heal'],
    warnings: ['Efecto puede tardar 2-4 semanas', 'No combinar con alcohol'],
  },
  
  // Hierbas para el Sistema Nervioso
  'ashwagandha': {
    id: 'ashwagandha',
    name: 'Ashwagandha',
    scientificName: 'Withania somnifera',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta de medicina ayurvédica de India.',
    },
    description: 'Adaptógeno para estrés crónico, ansiedad, fatiga adrenal.',
    mechanism: 'Withanólidos modulan eje HPA. Activación de receptores GABA.',
    indications: ['Estrés crónico', 'Ansiedad', 'Fatiga adrenal', 'Insomnio adaptativo', 'Baja libido', 'Déficit de atención'],
    contraindications: ['Embarazo', 'Lactancia', 'Hipertiroidismo', 'Enfermedades autoinmunes activas'],
    interactions: ['Potencia benzodiacepinas', 'Puede bajar glucemia'],
    dosage: 'Extracto KSM-66 (5% withanólidos): 300-600 mg/día.',
    synonyms: ['ashwagandha', 'withania', 'ginseng indio', 'winter cherry', 'somnifera'],
    warnings: ['Puede causar somnolencia', 'Monitorizar TSH si hay hipotiroidismo'],
  },
  'bacopa': {
    id: 'bacopa',
    name: 'Bacopa',
    scientificName: 'Bacopa monnieri',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta acuática de medicina ayurvédica.',
    },
    description: 'Nootrópico natural. Mejora memoria y concentración.',
    mechanism: 'Los bacósidos modulan receptores de acetilcolina y serotonina.',
    indications: ['Déficit de memoria', 'Concentración', 'Ansiedad', 'Epilepsia', 'Alzheimer inicial'],
    contraindications: ['Embarazo', 'Lactancia', 'Hipotiroidismo'],
    interactions: ['Antiepilépticos', 'Sedantes', 'Hormonas tiroideas'],
    dosage: 'Extracto (20-50% bacósidos): 150-300 mg/día.',
    synonyms: ['bacopa', 'bacopa monnieri', 'brahmi', 'water hyssop'],
    warnings: ['Efecto requiere 8-12 semanas', 'Puede causar sequedad bucal'],
  },
  'ginkgo': {
    id: 'ginkgo',
    name: 'Ginkgo Biloba',
    scientificName: 'Ginkgo biloba',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Árbol ancestral. El más antiguo del mundo.',
    },
    description: 'Vasodilatador cerebral. Mejora circulación y función cognitiva.',
    mechanism: 'Los ginkgólidos mejoran flujo sanguíneo y tienen efecto neuroprotector.',
    indications: ['Déficit de memoria', 'Vértigo', 'Zumbido de oídos', 'Claudicación intermitente', 'Demencia', 'Degeneración macular'],
    contraindications: ['Embarazo', 'Lactancia', 'Epilepsia'],
    interactions: ['Anticoagulantes', 'AINEs', 'Antidiabéticos'],
    dosage: 'Extracto (24-32% flavonas): 120-240 mg/día en 2-3 dosis.',
    synonyms: ['ginkgo', 'ginkgo biloba', 'fossil tree', 'maidenhair tree'],
    warnings: ['Puede aumentar riesgo de sangrado', 'Calidad variable'],
  },
  'ginseng': {
    id: 'ginseng',
    name: 'Ginseng',
    scientificName: 'Panax ginseng',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Raíz de Corea, China y Siberia. Mínimo 5-6 años de cultivo.',
    },
    description: 'Adaptógeno que aumenta resistencia al estrés.',
    mechanism: 'Las ginsenósidas modulan eje HPA. Mejora cognición y función inmune.',
    indications: ['Fatiga física y mental', 'Estrés y burnout', 'Déficit de atención', 'Recuperación post-enfermedad', 'Menopausia'],
    contraindications: ['Embarazo y lactancia', 'Hipertensión no controlada', 'Insomnio severo', 'Niños <12 años'],
    interactions: ['Warfarina', 'Estimulantes', 'Hipoglucemiantes'],
    dosage: 'Extracto (4-7% ginsenósidos): 200-400 mg/día. Ciclos de 2-3 semanas.',
    synonyms: ['ginseng', 'panax ginseng', 'ginseng coreano', 'ren shen', 'asian ginseng'],
    warnings: ['Efecto estimulante - no tomar por la tarde', 'Ciclar uso', 'No combinar con cafeína'],
  },
  'gotu-kola': {
    id: 'gotu-kola',
    name: 'Gotu Kola',
    scientificName: 'Centella asiatica',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta de medicina ayurvédica y asiática.',
    },
    description: 'Neuroprotector y vulnerario. Favorece síntesis de colágeno.',
    mechanism: 'Los asiaticósidos estimulan fibroblastos y síntesis de colágeno.',
    indications: ['Cicatrización', 'Celulitis', 'Estrías', 'Memoria', 'Ansiedad', 'Varices'],
    contraindications: ['Embarazo', 'Epilepsia', 'Cáncer'],
    interactions: ['Sedantes', 'Antidiabéticos', 'Antihipertensivos'],
    dosage: 'Extracto estandarizado: 60-180 mg/día.',
    synonyms: ['gotu kola', 'centella asiatica', 'brahmi', 'mandukaparni'],
    warnings: ['Puede causar fotosensibilidad', 'No usar en insuficiencia hepática'],
  },
  'griffonia': {
    id: 'griffonia',
    name: 'Griffonia',
    scientificName: 'Griffonia simplicifolia',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta africana. Semillas ricas en 5-HTP.',
    },
    description: 'Precursor de serotonina. Antidepresivo natural.',
    mechanism: '5-HTP es precursor inmediato de serotonina y melatonina.',
    indications: ['Depresión', 'Ansiedad', 'Insomnio', 'Migraña', 'Obesidad (control de apetito)', 'Fibromialgia'],
    contraindications: ['Embarazo', 'Lactancia', 'Antidepresivos ISRS'],
    interactions: ['ISRS', 'IMAOs', 'Carbidopa'],
    dosage: '5-HTP: 50-100 mg, 2-3 veces al día.',
    synonyms: ['griffonia', 'griffonia simplicifolia', '5-htp natural'],
    warnings: ['No combinar con antidepresivos sin supervisión', 'Puede causar náuseas'],
  },
  'hierba-de-san-juan': {
    id: 'hierba-de-san-juan',
    name: 'Hierba de San Juan',
    scientificName: 'Hypericum perforatum',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta europea. Usada desde la antigüedad.',
    },
    description: 'Antidepresivo natural para depresión leve a moderada.',
    mechanism: 'La hipericina inhibe recaptación de serotonina, noradrenalina y dopamina.',
    indications: ['Depresión leve a moderada', 'Ansiedad', 'Insomnio', 'Menopausia', 'Heridas'],
    contraindications: ['Embarazo', 'Lactancia', 'Trasplante de órganos'],
    interactions: ['ISRS', 'Anticonceptivos', 'Warfarina', 'Digoxina', 'Antirretrovirales'],
    dosage: 'Extracto estandarizado (0.3% hipericina): 300 mg, 3 veces al día.',
    synonyms: ['hierba de san juan', 'hypericum', 'st. john\'s wort', 'hipérico'],
    warnings: ['Induce CYP3A4 - múltiples interacciones', 'Fotosensibilidad', 'No combinar con ISRS'],
  },
  'l-teanina': {
    id: 'l-teanina',
    name: 'L-Teanina',
    scientificName: 'L-Teanina',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Aminoácido del té verde (Camellia sinensis).',
    },
    description: 'Promueve relajación sin somnolencia. Mejora atención.',
    mechanism: 'Aumenta ondas alfa cerebrales. Eleva GABA, dopamina y serotonina.',
    indications: ['Estrés y ansiedad', 'Mejora de concentración', 'Insomnio', 'Reducción de estrés por cafeína'],
    contraindications: ['Embarazo (datos limitados)', 'Lactancia (datos limitados)'],
    interactions: ['Sinergia con cafeína'],
    dosage: '100-200 mg 1-2 veces al día.',
    synonyms: ['teanina', 'L-theanine', 'suntheanine'],
    warnings: ['Efecto óptimo requiere varias semanas'],
  },
  'mucuna': {
    id: 'mucuna',
    name: 'Mucuna Pruriens',
    scientificName: 'Mucuna pruriens',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta tropical. Semillas ricas en L-DOPA.',
    },
    description: 'Fuente natural de L-DOPA. Para Parkinson y libido.',
    mechanism: 'L-DOPA es precursor de dopamina y adrenalina.',
    indications: ['Parkinson', 'Depresión', 'Baja libido', 'Fatiga', 'Síndrome de piernas inquietas'],
    contraindications: ['Embarazo', 'Psicosis', 'Melanoma'],
    interactions: ['Antihipertensivos', 'IMAOs', 'Antipsicóticos'],
    dosage: 'Extracto (15-20% L-DOPA): 5-10 g/día.',
    synonyms: ['mucuna', 'mucuna pruriens', 'velvet bean', 'cowitch'],
    warnings: [' Puede causar náuseas', 'No usar con IMAOs'],
  },
  'pasiflora': {
    id: 'pasiflora',
    name: 'Pasiflora',
    scientificName: 'Passiflora incarnata',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Flor de la pasión. Planta de América.',
    },
    description: 'Ansiolítica y sedante suave.',
    mechanism: 'Los flavonoides modulan receptores GABA.',
    indications: ['Ansiedad', 'Insomnio', 'Nerviosismo', 'Palpitaciones', 'Espasmos'],
    contraindications: ['Embarazo', 'Lactancia'],
    interactions: ['Sedantes', 'Benzodiacepinas', 'Anticoagulantes'],
    dosage: 'Extracto: 200-400 mg/día. Infusión: 0.5-2 g, 3-4 veces al día.',
    synonyms: ['pasiflora', 'passiflora', 'passion flower', 'flor de la pasión'],
    warnings: ['Puede potenciar sedantes'],
  },
  'rodiola': {
    id: 'rodiola',
    name: 'Rodiola',
    scientificName: 'Rhodiola rosea',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta adaptógena ártica y de montañas.',
    },
    description: 'Adaptógeno para estrés, fatiga y rendimiento.',
    mechanism: 'Los rosavinas modulan eje HPA y norepinefrina.',
    indications: ['Estrés', 'Fatiga', 'Rendimiento físico', 'Rendimiento mental', 'Depresión', 'Ansiedad'],
    contraindications: ['Embarazo', 'Lactancia', 'Epilepsia'],
    interactions: ['Anticoagulantes', 'Antidiabéticos'],
    dosage: 'Extracto (3% rosavinas): 200-400 mg/día.',
    synonyms: ['rodiola', 'rhodiola', 'golden root', 'artctic root', 'roseroot'],
    warnings: ['No tomar por la noche (estimulante)', 'Efecto rápido vs. otros adaptógenos'],
  },
  'salvia': {
    id: 'salvia',
    name: 'Salvia Officinalis',
    scientificName: 'Salvia officinalis',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta aromática mediterránea.',
    },
    description: 'Tónica cerebral y digestiva.',
    mechanism: 'Los diterpenos inhiben acetilcolinesterasa.',
    indications: ['Memoria', 'Concentración', 'Sofocos', 'Dolor de garganta', 'Encías sangrantes'],
    contraindications: ['Embarazo', 'Epilepsia', 'Cáncer hormono-dependiente'],
    interactions: ['Antidiabéticos', 'Anticoagulantes', 'Sedantes'],
    dosage: 'Infusión: 1-2 g de hojas, 2-3 veces al día.',
    synonyms: ['salvia', 'sage', 'salvia officinalis', 'salvia real'],
    warnings: ['Thujona en dosis altas puede ser neurotóxica', 'No exceder 2 semanas contínuas'],
  },
  'schisandra': {
    id: 'schisandra',
    name: 'Schisandra',
    scientificName: 'Schisandra chinensis',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Baya de 5 sabores. Medicina china tradicional.',
    },
    description: 'Adaptógeno y hepatoprotector.',
    mechanism: 'Los lignanos protegen hepatocitos y modulan eje HPA.',
    indications: ['Estrés', 'Fatiga', 'Hepatoprotección', 'Rendimiento', 'Insomnio', 'Tos'],
    contraindications: ['Embarazo', 'Epilepsia', 'Hipertensión'],
    interactions: ['Anticoagulantes', 'Antidiabéticos', 'Digoxina'],
    dosage: 'Extracto (9% schisandrins): 500 mg, 2 veces al día.',
    synonyms: ['schisandra', 'schisandra chinensis', 'five flavor berry', 'wu wei zi'],
    warnings: ['Generalmente bien tolerada'],
  },
  'tila': {
    id: 'tila',
    name: 'Tila',
    scientificName: 'Tilia cordata/platiphyllos',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Tilo. Árbol europeo muy común.',
    },
    description: 'Relajante suave, ansiolítica y febrífuga.',
    mechanism: 'Los flavonoides tienen efecto sedante y diaforético.',
    indications: ['Ansiedad', 'Insomnio', 'Resfriado', 'Cefalea tensional', 'Digestión nerviosa'],
    contraindications: ['Cardiopatía'],
    interactions: ['Sedantes', 'Antihipertensivos'],
    dosage: 'Infusión: 2-4 g de flores, 2-3 veces al día.',
    synonyms: ['tila', 'tilo', 'linden', 'lime flower', 'tilia'],
    warnings: ['Efecto leve', 'Uso prolongado puede afectar corazón'],
  },
  
  // Hierbas para el Sistema Inmunológico
  'equinacea': {
    id: 'equinacea',
    name: 'Equinácea',
    scientificName: 'Echinacea purpurea',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta de América del Norte.',
    },
    description: 'Inmunomodulador. Previene y trata infecciones.',
    mechanism: 'Estimula macrófagos, células NK y producción de citoquinas.',
    indications: ['Resfriados', 'Gripe', 'Infecciones urinarias', 'Heridas', 'Abscesos'],
    contraindications: ['Enfermedades autoinmunes', 'VIH/SIDA', 'Embarazo', 'Lactancia'],
    interactions: ['Inmunosupresores', 'Corticoides', 'Hepatotóxicos'],
    dosage: 'Tintura: 2-4 ml, 3 veces al día. Cápsulas: 300-500 mg, 3 veces al día.',
    synonyms: ['equinácea', 'echinacea', 'purple coneflower'],
    warnings: ['No usar continuamente más de 8 semanas', 'Alergia cruzada con Asteraceae'],
  },
  'propoleo': {
    id: 'propoleo',
    name: 'Própoleo',
    scientificName: 'Propolis',
    category: 'fitoterapia',
    origin: {
      type: 'animal',
      description: 'Sustancia resinosa de colmenas deabejas.',
    },
    description: 'Antimicrobiano natural, cicatrizante e inmunoestimulante.',
    mechanism: 'Los flavonoides tienen efecto antibacteriano, antiviral y antifúngico.',
    indications: ['Faringitis', 'Gingivitis', 'Heridas', 'Herpes', 'Acné', 'Infecciones vaginales'],
    contraindications: ['Alergia a productos apícolas', 'Asma alérgica'],
    interactions: ['Anticoagulantes'],
    dosage: 'Tintura: 20-30 gotas, 2-3 veces al día. Cápsulas: 500 mg/día.',
    synonyms: ['própoleo', 'propolis', 'bee glue'],
    warnings: ['Alergia a propóleo es posible', 'No usar en heridas profundas'],
  },
  'umbo-copahuite': {
    id: 'umbo-copahuite',
    name: 'Umbo Copahuite',
    scientificName: 'Myrtus communis',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Mirto o arrayán. Planta mediterránea.',
    },
    description: 'Antimicrobiano y astringente.',
    mechanism: 'El mirtuol tiene efecto antibacteriano y antiinflamatorio.',
    indications: ['Infecciones respiratorias', 'Cistitis', 'Diarrea', 'Heridas', 'Encías'],
    contraindications: ['Embarazo'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'Decocción: 10-15 g/l, 2-3 tazas al día.',
    synonyms: ['mirto', 'arrayán', 'myrtle', 'myrtus communis'],
    warnings: ['Efecto suave'],
  },
  
  // Hierbas para el Sistema Cardiovascular
  'ajo': {
    id: 'ajo',
    name: 'Ajo',
    scientificName: 'Allium sativum',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta bulbosa. Condimento y medicina ancestral.',
    },
    description: 'Cardioprotector, hipotensor y antimicrobiano.',
    mechanism: 'La alicina tiene efecto hipotensor y hipolipemiante.',
    indications: ['Hipertensión', 'Hipercolesterolemia', 'Aterosclerosis', 'Infecciones', 'Verrugas'],
    contraindications: ['Cirugía (suspender 2 semanas)', 'Embarazo'],
    interactions: ['Anticoagulantes', 'VIH medicamentos'],
    dosage: 'Ajo fresco: 1-2 dientes/día. Extracto: seguir indicaciones.',
    synonyms: ['ajo', 'garlic', 'allium sativum'],
    warnings: ['Mal aliento y olor corporal', 'Puede causar reflujo'],
  },
  'espino-blanco': {
    id: 'espino-blanco',
    name: 'Espino Blanco',
    scientificName: 'Crataegus oxyacantha',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Arbusto europeo. Flores y bayas.',
    },
    description: 'Cardiotónico y vasodilatador coronario.',
    mechanism: 'Los flavonoides mejoran flujo coronario y contractilidad.',
    indications: ['Insuficiencia cardíaca leve', 'Angina', 'Palpitaciones', 'Arritmias', 'Ansiedad cardíaca'],
    contraindications: ['Hipotensión severa'],
    interactions: ['Digoxina', 'Antihipertensivos', 'Anticoagulantes'],
    dosage: 'Extracto: 160-900 mg/día de flavonoides.',
    synonyms: ['espino blanco', 'hawthorn', 'crataegus', 'espino albar'],
    warnings: ['Efecto requiere semanas', 'No sustituye监护型药物'],
  },
  'muerdago': {
    id: 'muerdago',
    name: 'Muérdago',
    scientificName: 'Viscum album',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta semiparásita. Usada en terapia anthroposófica.',
    },
    description: 'Hipotensor e inmunoestimulante.',
    mechanism: 'Lectinas e viscotoxinas modulan sistema inmune.',
    indications: ['Hipertensión', 'Artrosis', 'Cáncer (complementario)', 'Esclerosis múltiple'],
    contraindications: ['Embarazo', 'Enfermedades autoinmunes activas'],
    interactions: ['Inmunosupresores'],
    dosage: 'Extracto estandarizado: seguir protocolo médico.',
    synonyms: ['muerdago', 'mistletoe', 'viscum album', 'liga'],
    warnings: ['NO usar frutos (tóxicos)', 'Uso supervisión médica'],
  },
  'olivo': {
    id: 'olivo',
    name: 'Olivo',
    scientificName: 'Olea europaea',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Árbol mediterráneo. Hojas y aceite.',
    },
    description: 'Hipotensor y vasodilatador.',
    mechanism: 'La oleuropeína tiene efecto vasodilatador y antiinflamatorio.',
    indications: ['Hipertensión', 'Aterosclerosis', 'Diabetes', 'Artritis'],
    contraindications: ['Hipotensión'],
    interactions: ['Antihipertensivos', 'Anticoagulantes'],
    dosage: 'Extracto de hojas: 500-1000 mg/día.',
    synonyms: ['olivo', 'olive', 'olive leaf', 'olea europaea'],
    warnings: ['Puede bajar mucho la presión'],
  },
  
  // Hierbas para el Sistema Respiratorio
  'alho-silvestre': {
    id: 'alho-silvestre',
    name: 'alho-silvestre',
    scientificName: 'Allium ursinum',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Ajo silvestre. Planta europea.',
    },
    description: 'Antimicrobiano y cardioprotector.',
    mechanism: 'Similar al ajo cultivado pero más suave.',
    indications: ['Infecciones respiratorias', 'Aterosclerosis', 'Hipertensión'],
    contraindications: ['Cirugía (suspender)'],
    interactions: ['Anticoagulantes'],
    dosage: 'Tintura: 1-2 ml, 3 veces al día.',
    synonyms: ['ajo silvestre', 'wild garlic', 'ramps', 'allium ursinum'],
    warnings: ['Olor menos intenso que ajo'],
  },
  'grindelia': {
    id: 'grindelia',
    name: 'Grindelia',
    scientificName: 'Grindelia robusta',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta americana.',
    },
    description: 'Expectorante y antiespasmódico respiratorio.',
    mechanism: 'Los resínoles tienen efecto expectorante y antiinflamatorio bronquial.',
    indications: ['Tos seca irritativa', 'Bronquitis', 'Asma', 'Faringitis'],
    contraindications: ['Embarazo'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'Infusión: 2-4 g/día. Tintura: 2-4 ml, 3 veces al día.',
    synonyms: ['grindelia', 'gumweed', 'grindelia robusta'],
    warnings: ['Puede causar náuseas'],
  },
  'gordolobo': {
    id: 'gordolobo',
    name: 'Gordolobo',
    scientificName: 'Verbascum thapsus',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta herbácea. Flores.',
    },
    description: 'Expectorante y demulcente.',
    mechanism: 'Los mucílagos suavizan mucosas irritadas.',
    indications: ['Tos seca', 'Bronquitis', 'Dolor de garganta', 'Laringitis', 'Asma'],
    contraindications: ['Embarazo', 'Lactancia'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'Infusión: 1-2 g de flores, 2-3 veces al día.',
    synonyms: ['gordolobo', 'mullein', 'verbascum', 'verbasco'],
    warnings: ['Puede irritar piel sensible'],
  },
  'hisopo': {
    id: 'hisopo',
    name: 'Hisopo',
    scientificName: 'Hyssopus officinalis',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta mediterránea. Hierba aromática.',
    },
    description: 'Expectorante y antiséptico.',
    mechanism: 'Aceites esenciales tienen efecto expectorante y antimicrobiano.',
    indications: ['Bronquitis', 'Tos', 'Resfriado', 'Gripe', 'Faringitis'],
    contraindications: ['Embarazo', 'Epilepsia'],
    interactions: ['Antiepilépticos'],
    dosage: 'Infusión: 1-2 g, 3 veces al día.',
    synonyms: ['hisopo', 'hyssop', 'hyssopus officinalis'],
    warnings: ['No usar aceite esencial internamente'],
  },
  'liquen-de-islandia': {
    id: 'liquen-de-islandia',
    name: 'Liquen de Islandia',
    scientificName: 'Cetraria islandica',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Liquen ártico. Muy resistente.',
    },
    description: 'Demulcente y antibiótico suave.',
    mechanism: 'Los mucílagos protegen mucosas. Ácido úsnico tiene efecto antimicrobiano.',
    indications: ['Tos seca', 'Dolor de garganta', 'Bronquitis', 'Gastritis', 'Úlcera'],
    contraindications: ['Embarazo', 'Lactancia'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'Decocción: 1.5-2 g, 2-3 veces al día.',
    synonyms: ['liquen de islandia', 'iceland moss', 'cetrelia islandica'],
    warnings: ['Efecto requiere uso prolongado'],
  },
  'marron-indio': {
    id: 'marron-indio',
    name: 'Marrón Indio',
    scientificName: 'Aesculus hippocastanum',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Castaño de Indias. Semillas.',
    },
    description: 'Venotónico y antiinflamatorio.',
    mechanism: 'La escina reduce permeabilidad capilar y edema.',
    indications: ['Insuficiencia venosa', 'Hemorroides', 'Varices', 'Piernas pesadas', 'Celulitis'],
    contraindications: ['Embarazo', 'Insuficiencia renal'],
    interactions: ['Anticoagulantes', 'Hepatotóxicos'],
    dosage: 'Extracto (50 mg aescina): 2 veces al día.',
    synonyms: ['castaño de Indias', 'horse chestnut', 'aesculus', 'marronnier'],
    warnings: ['Semillas crudas son tóxicas', 'No confundir con castañas comestibles'],
  },
  'pelargonio': {
    id: 'pelargonio',
    name: 'Pelargonio',
    scientificName: 'Pelargonium sidoides',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Geranio sudafricano.',
    },
    description: 'Antiviral y expectorante respiratorio.',
    mechanism: 'Cumarinas y gallotaninos tienen efecto antiviral directo.',
    indications: ['Resfriado', 'Bronquitis aguda', 'Sinusitis', 'Faringitis'],
    contraindications: ['Embarazo', 'Lactancia', 'Enfermedades hepáticas'],
    interactions: ['Warfarina'],
    dosage: 'Extracto: 30-60 gotas, 3 veces al día.',
    synonyms: ['pelargonio', 'pelargonium', 'umckaloabo', 'south african geranium'],
    warnings: ['Puede causar malestar gastrointestinal'],
  },
  'plantago': {
    id: 'plantago',
    name: 'Plantago',
    scientificName: 'Plantago lanceolata',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Llantén. Planta muy común.',
    },
    description: 'Demulcente y expectorante.',
    mechanism: 'Los mucílagos cubren y protegen mucosas irritadas.',
    indications: ['Tos seca', 'Dolor de garganta', 'Bronquitis', 'Conjuntivitis', 'Heridas'],
    contraindications: ['Embarazo (datos limitados)'],
    interactions: ['Digitálicos (puede reducir absorción)'],
    dosage: 'Infusión: 2-4 g, 3-4 veces al día.',
    synonyms: ['plantago', 'llantén', 'plantain', 'ribwort plantain'],
    warnings: ['Efecto suave pero constante'],
  },
  'tomillo': {
    id: 'tomillo',
    name: 'Tomillo',
    scientificName: 'Thymus vulgaris',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Hierba mediterránea. Condimento popular.',
    },
    description: 'Antiséptico, expectorante y antiespasmódico.',
    mechanism: 'El timol tiene efecto antibacteriano y antiviral.',
    indications: ['Tos productiva', 'Bronquitis', 'Resfriado', 'Gripe', 'Amigdalitis', 'Cistitis'],
    contraindications: ['Embarazo'],
    interactions: ['Anticoagulantes'],
    dosage: 'Infusión: 1-2 g, 3-4 veces al día.',
    synonyms: ['tomillo', 'thyme', 'thymus vulgaris', 'thym'],
    warnings: ['No usar aceite esencial internamente sin supervisión'],
  },
  
  // Hierbas para el Sistema Urinario
  'abedul': {
    id: 'abedul',
    name: 'Abedul',
    scientificName: 'Betula pendula',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Árbol europeo. Hojas y savia.',
    },
    description: 'Diurético y antiinflamatorio urinario.',
    mechanism: 'Los flavonoides y sales de potasio tienen efecto diurético.',
    indications: ['Cistitis', 'Retención de líquidos', 'Cálculos renales', 'Gota', 'Edema'],
    contraindications: ['Insuficiencia cardíaca', 'Insuficiencia renal'],
    interactions: ['Diuréticos (potencia efecto)', 'Litio'],
    dosage: 'Infusión: 2-4 g de hojas, 2-3 veces al día.',
    synonyms: ['abedul', 'birch', 'betula', 'silver birch'],
    warnings: ['Riesgo de hipopotasemia con uso prolongado'],
  },
  'gayuba': {
    id: 'gayuba',
    name: 'Gayuba',
    scientificName: 'Arctostaphylos uva-ursi',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Bearsberry. Planta boreal.',
    },
    description: 'Antiséptico urinario natural.',
    mechanism: 'La arbutina se convierte en hidroquinona antibacterial en orina.',
    indications: ['Cistitis', 'Uretritis', 'Pielonefritis', 'Incontinencia urinaria'],
    contraindications: ['Embarazo', 'Lactancia', 'Enfermedad renal', 'Niños'],
    interactions: ['Litio', 'Diuréticos'],
    dosage: 'Infusión: 1.5-4 g, 2-4 veces al día.',
    synonyms: ['gayuba', 'uva ursi', 'bearberry', 'arctostaphylos'],
    warnings: ['NO usar más de 1-2 semanas', 'Pode ser hepatotóxica', 'Orina se vuelve verde'],
  },
  'ortiga-verde': {
    id: 'ortiga-verde',
    name: 'Ortiga Verde',
    scientificName: 'Urtica dioica',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Ortiga común. Muy nutritiva.',
    },
    description: 'Diurética, depurativa y antianémica.',
    mechanism: 'Rica en hierro, vitaminas y minerales. Efecto diurético suave.',
    indications: ['Anemia', 'Retención de líquidos', 'Cistitis', 'Artritis', 'Próstata', 'Alergias'],
    contraindications: ['Edema por insuficiencia cardíaca', 'Insuficiencia renal'],
    interactions: ['Anticoagulantes', 'Antihipertensivos', 'Diabetes medicamentos'],
    dosage: 'Infusión: 2-4 g, 3-4 veces al día.',
    synonyms: ['ortiga', 'nettle', 'urtica', 'stinging nettle'],
    warnings: ['Fresca pica y puede causar alergias cutáneas'],
  },
  'pierna': {
    id: 'pierna',
    name: 'Pierna',
    scientificName: 'Epilobium angustifolium',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Adelfilla. Planta europea.',
    },
    description: 'Antiinflamatorio prostático y urinario.',
    mechanism: 'Los polifenoles tienen efecto antiinflamatorio prostático.',
    indications: ['Hiperplasia prostática benigna', 'Prostatitis', 'Cistitis', 'Enuresis nocturna'],
    contraindications: ['Embarazo'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'Infusión: 1.5-2 g, 2-3 veces al día.',
    synonyms: ['pierna', 'willowherb', 'fireweed', 'epilobio'],
    warnings: ['Efecto requiere uso prolongado'],
  },
  'vara-de-oro': {
    id: 'vara-de-oro',
    name: 'Vara de Oro',
    scientificName: 'Solidago virgaurea',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta europea común.',
    },
    description: 'Diurética y antiinflamatoria urinaria.',
    mechanism: 'Flavonoides y saponinas tienen efecto diurético y antiinflamatorio.',
    indications: ['Cistitis', 'Uretritis', 'Cálculos renales', 'Retención de líquidos', 'Gota'],
    contraindications: ['Edema cardíaco', 'Insuficiencia renal'],
    interactions: ['Diuréticos', 'Litio'],
    dosage: 'Infusión: 2-4 g, 3-4 veces al día.',
    synonyms: ['vara de oro', 'goldenrod', 'solidago', 'verga de oro'],
    warnings: ['Efecto suave pero efectivo'],
  },
  
  // Hierbas para el Sistema Locomotor
  'harpagofito': {
    id: 'harpagofito',
    name: 'Harpagofito',
    scientificName: 'Harpagophytum procumbens',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta del desierto de Kalahari.',
    },
    description: 'Antiinflamatorio natural para articulaciones.',
    mechanism: 'Los harpagósidos inhiben COX y LOX. Efecto analgésico.',
    indications: ['Osteoartritis', 'Dolor lumbar', 'Tendinitis', 'Fibromialgia', 'Cefalea tensional'],
    contraindications: ['Embarazo', 'Lactancia', 'Úlcera péptica', 'Cálculos biliares'],
    interactions: ['Anticoagulantes', 'Antidiabéticos', 'Antihipertensivos'],
    dosage: 'Extracto (3% harpagósidos): 600-1200 mg/día.',
    synonyms: ['harpagofito', 'garra del diablo', 'devil\'s claw', 'harpagophytum'],
    warnings: ['Amargo - puede causar náuseas', 'No usar con úlcera'],
  },
  'cola-de-caballo': {
    id: 'cola-de-caballo',
    name: 'Cola de Caballo',
    scientificName: 'Equisetum arvense',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Helecho primitivo. Rico en sílice.',
    },
    description: 'Diurético, remineralizante y cicatrizante.',
    mechanism: 'Rica en sílice y potasio. Favorece síntesis de colágeno.',
    indications: ['Edema', 'Cálculos urinarios', 'Fragilidad de uñas', 'Heridas', 'Osteoporosis', 'Fragilidad capilar'],
    contraindications: ['Embarazo', 'Lactancia', 'Insuficiencia cardíaca', 'Insuficiencia renal'],
    interactions: ['Diuréticos', 'Litio', 'Digital'],
    dosage: 'Infusión: 2-4 g, 3-4 veces al día.',
    synonyms: ['cola de caballo', 'horsetail', 'equisetum'],
    warnings: ['Riesgo de hipopotasemia', 'Contiene tiaminasa (destruir con calor)'],
  },
  
  // Hongos Medicinales
  'reishi': {
    id: 'reishi',
    name: 'Reishi',
    scientificName: 'Ganoderma lucidum',
    category: 'fitoterapia',
    origin: {
      type: 'microorganismo',
      description: 'Hongo medicinal chino con más de 2000 años.',
    },
    description: 'Inmunomodulador, antioxidante y adaptógeno.',
    mechanism: 'Beta-glucanos activan macrófagos y células NK.',
    indications: ['Optimización inmune', 'Alergias', 'Apoyo hepático', 'Colesterol', 'Ansiedad', 'Sueño'],
    contraindications: ['Cirugía (suspender 2 semanas)', 'Embarazo', 'Enfermedades autoinmunes'],
    interactions: ['Anticoagulantes', 'Hipoglucemiantes', 'Inmunosupresores'],
    dosage: 'Extracto (10:1): 1-2 g/día.',
    synonyms: ['reishi', 'ganoderma', 'lingzhi', 'reishi rojo'],
    warnings: ['Calidad variable', 'Efecto anticoagulante leve'],
  },
  'cordyceps': {
    id: 'cordyceps',
    name: 'Cordyceps',
    scientificName: 'Cordyceps sinensis',
    category: 'fitoterapia',
    origin: {
      type: 'microorganismo',
      description: 'Hongo parásito del Tíbet.',
    },
    description: 'Adaptógeno para energía, rendimiento y función renal.',
    mechanism: 'Cordicepina modula ATP y función adrenal.',
    indications: ['Fatiga', 'Rendimiento deportivo', 'Función renal', 'Inmunidad', 'Libido', 'Diabetes'],
    contraindications: ['Embarazo', 'Lactancia', 'Cáncer hormono-dependiente'],
    interactions: ['Anticoagulantes', 'Inmunosupresores'],
    dosage: '1-3 g/día de extracto estandarizado.',
    synonyms: ['cordyceps', 'cordyceps sinensis', 'hongo oruga', 'caterpillar fungus'],
    warnings: ['Calidad muy variable', 'Preferir extracto certificado'],
  },
  'maitake': {
    id: 'maitake',
    name: 'Maitake',
    scientificName: 'Grifola frondosa',
    category: 'fitoterapia',
    origin: {
      type: 'microorganismo',
      description: 'Hongo japonés. "Hongo danzante".',
    },
    description: 'Inmunomodulador y potencial anticancerígeno.',
    mechanism: 'Beta-glucanos (fracción D) activan células inmunes.',
    indications: ['Apoyo inmune', 'Quimioterapia (complementario)', 'Diabetes', 'Colesterol', 'Presión arterial'],
    contraindications: ['Embarazo', 'Lactancia'],
    interactions: ['Anticoagulantes', 'Hipoglucemiantes'],
    dosage: 'Extracto: 0.5-1.5 g/día.',
    synonyms: ['maitake', 'hen of the woods', 'grifola', 'dancing mushroom'],
    warnings: ['Generalmente seguro'],
  },
  'shiitake': {
    id: 'shiitake',
    name: 'Shiitake',
    scientificName: 'Lentinula edodes',
    category: 'fitoterapia',
    origin: {
      type: 'microorganismo',
      description: 'Hongo comestible japonés. Cultivado ampliamente.',
    },
    description: 'Inmunoestimulante y cardiovascular.',
    mechanism: 'Lentinano (beta-glucano) modula sistema inmune.',
    indications: ['Apoyo inmune', 'Colesterol alto', 'Presión arterial', 'Cáncer (complementario)'],
    contraindications: ['Alergia a hongos'],
    interactions: ['Anticoagulantes'],
    dosage: '3-6 g de setas secas o extracto equivalente.',
    synonyms: ['shiitake', 'lentinula edodes', 'shiitake mushroom'],
    warnings: ['Setas crudas pueden causar dermatitis'],
  },
  'hericium': {
    id: 'hericium',
    name: 'Hericium',
    scientificName: 'Hericium erinaceus',
    category: 'fitoterapia',
    origin: {
      type: 'microorganismo',
      description: 'Hongo erizado. "Barba de chivo".',
    },
    description: 'Neuroprotector y nootrópico.',
    mechanism: 'Hericenonas estimulan factor de crecimiento nervioso (NGF).',
    indications: ['Memoria', 'Concentración', 'Alzheimer', 'Neuropatía', 'Ansiedad', 'Depresión'],
    contraindications: ['Alergia a hongos'],
    interactions: ['Sin interacciones significativas'],
    dosage: 'Extracto: 500-1500 mg/día.',
    synonyms: ['hericium', 'lion\'s mane', 'yamabushitake', 'crinière de lion'],
    warnings: ['Generalmente seguro'],
  },
  
  // Hierbas para Piel y Tejido Conjuntivo
  'aloe-vera': {
    id: 'aloe-vera',
    name: 'Aloe Vera',
    scientificName: 'Aloe barbadensis miller',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta suculenta. Usada desde antigüedad.',
    },
    description: 'Cicatrizante, hidratante y antiinflamatoria.',
    mechanism: 'Polisacáridos y anthraquinonas promueven curación.',
    indications: ['Quemaduras', 'Heridas', 'Eccema', 'Psoriasis', 'Acné', 'Picaduras', 'Radiación'],
    contraindications: ['Embarazo (interno)', 'Alergia a Liliaceae'],
    interactions: ['Hipoglucemiantes (puede potenciar)'],
    dosage: 'Gel tópico: aplicar 2-3 veces al día. Jugo: 30 ml/día.',
    synonyms: ['aloe vera', 'aloe', 'aloe barbadensis', 'burn plant'],
    warnings: ['Látex de aloe (amarillo) es laxante y potencialmente carcinógeno', 'NO usar látex internamente'],
  },
  'calendula-vera': {
    id: 'calendula-vera',
    name: 'Caléndula',
    scientificName: 'Calendula officinalis',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Flor de Asteraceae. Muy común.',
    },
    description: 'Cicatrizante, antiinflamatoria y antiséptica.',
    mechanism: 'Triterpenoides reducen inflamación y promueven эпителизацию.',
    indications: ['Heridas', 'Queimaduras', 'Dermatitis del pañal', 'Eccema', 'Úlceras', 'Gingivitis'],
    contraindications: ['Alergia a Asteraceae'],
    interactions: ['Sedantes (puede potenciar)'],
    dosage: 'Tópico: pomada o crema 2-3 veces al día. Infusión para enjuagues.',
    synonyms: ['caléndula', 'marigold', 'calendula officinalis'],
    warnings: ['Uso tópico generalmente seguro'],
  },
  'hipérico': {
    id: 'hipérico',
    name: 'Hipérico (uso tópico)',
    scientificName: 'Hypericum perforatum',
    category: 'fitoterapia',
    origin: {
      type: 'planta',
      description: 'Planta europea. Uso interno ver Hierba de San Juan.',
    },
    description: 'Cicatrizante y antiinflamatorio tópico.',
    mechanism: 'Hipericina tiene efecto antiviral y cicatrizante tópico.',
    indications: ['Heridas', 'Quemaduras', 'Neuralgia', 'Hemorroides', 'Eccema'],
    contraindications: ['Alergia a Hypericum'],
    interactions: ['Fotosensibilización con otros fármacos'],
    dosage: 'Aceite o pomada: aplicar 1-2 veces al día.',
    synonyms: ['hipérico tópico', 'st johns wort topical', 'hypericum topical'],
    warnings: ['Uso tópico NO tiene mismas interacciones que interno'],
  },
};

// Función para combinar todas las bases de datos
export function getExtendedIngredientDatabase(): Record<string, ExtendedIngredientInfo> {
  return {
    ...HOMEOPATHY_DATABASE,
    ...HERBAL_DATABASE,
  };
}

// Función para buscar ingrediente
export function findExtendedIngredient(query: string): ExtendedIngredientInfo | null {
  const normalizedQuery = query.toLowerCase().trim();
  const db = getExtendedIngredientDatabase();
  
  // Búsqueda directa
  if (db[normalizedQuery]) {
    return db[normalizedQuery];
  }
  
  // Búsqueda por sinónimos
  for (const [key, ingredient] of Object.entries(db)) {
    if (ingredient.synonyms.some(s => s.toLowerCase().includes(normalizedQuery))) {
      return ingredient;
    }
    if (ingredient.name.toLowerCase().includes(normalizedQuery)) {
      return ingredient;
    }
  }
  
  return null;
}

// Función para obtener estadísticas
export function getExtendedIngredientStats(): { total: number; homeopatia: number; fitoterapia: number } {
  return {
    total: Object.keys(getExtendedIngredientDatabase()).length,
    homeopatia: Object.keys(HOMEOPATHY_DATABASE).length,
    fitoterapia: Object.keys(HERBAL_DATABASE).length,
  };
}
