-- Insertar minerales homeopáticos nuevos

INSERT INTO extended_ingredients (ingredient_key, name, scientific_name, category, origin_type, origin_description, description, mechanism, indications, contraindications, interactions, dosage, synonyms) VALUES
('aurum-metallicum', 'Aurum Metallicum', 'Oro metálico (Au)', 'homeopatia', 'mineral', 'Oro metálico. Metal precioso.', 'Remedio para depresión profunda, ideas suicidas y trastornos cardíacos.', 'Actúa sobre el plano mental y cardíaco. Regula la circulación.', ARRAY['Depresión con ideas suicidas', 'Melancolía profunda', 'Palpitaciones', 'Hipertensión', 'Aterosclerosis', 'Insomnio de madrugada'], ARRAY['Ninguna bajo supervisión médica'], ARRAY['Precaución con tratamientos psiquiátricos'], 'CH 6 a CH 15: 3-5 gránulos, 1-2 veces al día.', ARRAY['aurum met', 'oro metálico', 'aurum metallicum', 'gold metallic'])
ON CONFLICT (ingredient_key) DO UPDATE SET name = EXCLUDED.name, scientific_name = EXCLUDED.scientific_name, description = EXCLUDED.description, updated_at = NOW();

INSERT INTO extended_ingredients (ingredient_key, name, scientific_name, category, origin_type, origin_description, description, mechanism, indications, contraindications, interactions, dosage, synonyms) VALUES
('zincum-metallicum', 'Zincum Metallicum', 'Zinc metálico (Zn)', 'homeopatia', 'mineral', 'Zinc metálico. Oligoelemento esencial.', 'Remedio para debilidad nerviosa, síndrome de piernas inquietas y temblores.', 'Modula la transmisión nerviosa y el sistema nervioso central.', ARRAY['Síndrome de piernas inquietas', 'Temblores', 'Epilepsia', 'Fatiga mental extrema', 'Insomnio', 'Depresión con agotamiento', 'Neuralgia facial'], ARRAY['Ninguna bajo supervisión médica'], ARRAY['Precaución con quelantes de zinc'], 'CH 6 a CH 15: 3-5 gránulos, 1-2 veces al día.', ARRAY['zincum met', 'zinc metálico homeopático', 'zincum'])
ON CONFLICT (ingredient_key) DO UPDATE SET name = EXCLUDED.name, scientific_name = EXCLUDED.scientific_name, description = EXCLUDED.description, updated_at = NOW();

INSERT INTO extended_ingredients (ingredient_key, name, scientific_name, category, origin_type, origin_description, description, mechanism, indications, contraindications, interactions, dosage, synonyms) VALUES
('plumbum-metallicum', 'Plumbum Metallicum', 'Plomo metálico (Pb)', 'homeopatia', 'mineral', 'Plomo metálico. Metal tóxico en estado bruto.', 'Remedio para parálisis, dolor nervioso intenso y deterioro mental.', 'Actúa sobre el sistema nervioso y músculos. Analgésico potente.', ARRAY['Parálisis', 'Dolor nervioso intenso', 'Esclerosis lateral amiotrófica', 'Neuralgia del trigémino', 'Contracciones musculares', 'Deterioro mental progresivo'], ARRAY['Ninguna bajo supervisión médica'], ARRAY['Precaución con tratamientos neurológicos'], 'CH 6 a CH 15: 3-5 gránulos, 1-2 veces al día.', ARRAY['plumbum met', 'plomo metálico', 'lead metallic'])
ON CONFLICT (ingredient_key) DO UPDATE SET name = EXCLUDED.name, scientific_name = EXCLUDED.scientific_name, description = EXCLUDED.description, updated_at = NOW();

INSERT INTO extended_ingredients (ingredient_key, name, scientific_name, category, origin_type, origin_description, description, mechanism, indications, contraindications, interactions, dosage, synonyms) VALUES
('cuprum-metallicum', 'Cuprum Metallicum', 'Cobre metálico (Cu)', 'homeopatia', 'mineral', 'Cobre metálico. Oligoelemento esencial.', 'Remedio para calambres, espasmos y convulsiones.', 'Regula la transmisión neuromuscular y alivia espasmos.', ARRAY['Calambres musculares', 'Espasmos', 'Convulsiones', 'Tos ferina', 'Asma con espasmos', 'Cólicos', 'Epilepsia'], ARRAY['Ninguna bajo supervisión médica'], ARRAY['Precaución con tratamientos anticonvulsivos'], 'CH 6 a CH 15: 3-5 gránulos, cada 15-30 min en crisis agudas.', ARRAY['cuprum met', 'cobre metálico', 'copper metallic'])
ON CONFLICT (ingredient_key) DO UPDATE SET name = EXCLUDED.name, scientific_name = EXCLUDED.scientific_name, description = EXCLUDED.description, updated_at = NOW();

INSERT INTO extended_ingredients (ingredient_key, name, scientific_name, category, origin_type, origin_description, description, mechanism, indications, contraindications, interactions, dosage, synonyms) VALUES
('argentum-nitricum', 'Argentum Nitricum', 'Nitrato de plata (AgNO3)', 'homeopatia', 'mineral', 'Nitrato de plata. Sal soluble.', 'Remedio para ansiedad anticipatoria, miedo a las alturas y problemas digestivos.', 'Actúa sobre el sistema nervioso y digestivo.', ARRAY['Ansiedad anticipatoria', 'Miedo a las alturas', 'Miedo a hablar en público', 'Diarrea nervosa', 'Gastritis', 'Úlcera gástrica', 'Temblores'], ARRAY['Ninguna bajo supervisión médica'], ARRAY['Precaución con tratamientos psiquiátricos'], 'CH 6 a CH 15: 3-5 gránulos, 2-3 veces al día.', ARRAY['argentum nit', 'nitrato de plata', 'silver nitrate'])
ON CONFLICT (ingredient_key) DO UPDATE SET name = EXCLUDED.name, scientific_name = EXCLUDED.scientific_name, description = EXCLUDED.description, updated_at = NOW();

INSERT INTO extended_ingredients (ingredient_key, name, scientific_name, category, origin_type, origin_description, description, mechanism, indications, contraindications, interactions, dosage, synonyms) VALUES
('alumina', 'Alumina', 'Óxido de aluminio (Al2O3)', 'homeopatia', 'mineral', 'Óxido de aluminio. Corindón.', 'Remedio para sequedad de mucosas y estreñimiento crónico.', 'Regula la secreción de mucosas y el tránsito intestinal.', ARRAY['Estreñimiento crónico', 'Sequedad de mucosas', 'Ojos secos', 'Boca seca', 'Tos seca', 'Piel seca', 'Confusión mental'], ARRAY['Ninguna bajo supervisión médica'], ARRAY['Precaución con antiácidos'], 'CH 6 a CH 15: 3-5 gránulos, 1-2 veces al día.', ARRAY['alumina', 'óxido de aluminio', 'aluminum oxide'])
ON CONFLICT (ingredient_key) DO UPDATE SET name = EXCLUDED.name, scientific_name = EXCLUDED.scientific_name, description = EXCLUDED.description, updated_at = NOW();
