#!/usr/bin/env python3
"""Añade ingredientes nuevos para sistemas poco representados (Ronda 16)."""
import json
from pathlib import Path

DATA_DIR = Path('src/db/seeders/data')

existing_ids = set()
for f in ['fitoterapia', 'homeopatia', 'aceites', 'vitaminas_minerales']:
    data = json.load(open(DATA_DIR / f'{f}.json'))
    for ing in data['ingredientes']:
        existing_ids.add(ing['id'])

new_ingredientes = [
    {
        "id": "criptoxantina",
        "nombre": "Criptoxantina",
        "nombresAlternativos": ["Beta-criptoxantina", "Cryptoxanthin"],
        "nombreCientifico": "Beta-cryptoxanthin",
        "familia": "Carotenoide (xantofila)",
        "categoria": "vitamina",
        "sistemas": ["ocular", "inmune"],
        "indicaciones": ["antioxidante", "ocular", "inmunidad", "articular"],
        "descripcion": "Carotenoide provitaminico A con actividad antioxidante y antiinflamatoria; precursor de vitamina A retinol.",
        "mecanismoAccion": "Se convierte en retinol (vitamina A) y modula vias antiinflamatorias via NF-kB; protege epitelio pigmentario retiniano.",
        "nivelEvidencia": "B",
        "parteUsada": "Sintesis/extracto natural (Citrus reticulata, papaya)",
        "formasPresentacion": ["Capsulas (extracto natural)"],
        "tiempoEfecto": "4-8 semanas",
        "duracionTratamiento": "Continuo",
        "advertencias": ["Dosis altas pueden causar carotenodermia"],
        "interaccionesMedicamentosas": ["Orlistat (reduce absorcion)", "Colestiramina"],
        "tags": ["carotenoide", "retinol", "antioxidante", "retina", "pro-vitamina A"],
        "metadata": {"fechaCreacion": "2026-08-10", "fuente": "NIH ODS Fact Sheet + J. Nutr. reviews"}
    },
    {
        "id": "meso_zeaxantina",
        "nombre": "Meso-zeaxantina",
        "nombresAlternativos": ["Meso-zeaxanthin", "MZ", "3R,3S-zeaxantina"],
        "nombreCientifico": "3R,3S-zeaxanthin",
        "familia": "Xantofila (carotenoide)",
        "categoria": "vitamina",
        "sistemas": ["ocular"],
        "indicaciones": ["ocular", "antioxidante", "degeneracion macular"],
        "descripcion": "Isomero de zeaxantina central en la macula; potente filtro de luz azul y antioxidante retiniano.",
        "mecanismoAccion": "Se acumula en la macula central (donde es mas abundante que zeaxantina y luteina); filtra luz azul y neutraliza especies reactivas de oxigeno.",
        "nivelEvidencia": "A",
        "parteUsada": "Sintesis (a partir de luteina)",
        "formasPresentacion": ["Capsulas (formula AREDS2 con luteina+zeaxantina+meso-zeaxantina)"],
        "tiempoEfecto": "8-12 semanas",
        "duracionTratamiento": "Continuo",
        "advertencias": ["Sin efectos adversos conocidos a dosis usuales"],
        "interaccionesMedicamentosas": [],
        "tags": ["xantofila", "macula", "luz azul", "AREDS2", "antioxidante retiniano"],
        "metadata": {"fechaCreacion": "2026-08-10", "fuente": "AREDS2 trial (NEJM 2014) + CREST trial"}
    },
    {
        "id": "ginkgo_biloba_ocular",
        "nombre": "Ginkgo Biloba Extracto (Ocular)",
        "nombresAlternativos": ["Ginkgo flavonoides", "EGB 761 oftalmico"],
        "nombreCientifico": "Ginkgo biloba",
        "familia": "Ginkgoaceae",
        "categoria": "fitoterapia",
        "sistemas": ["ocular", "cardiovascular", "nervioso"],
        "indicaciones": ["ocular", "glaucoma", "circulacion", "cognitivo"],
        "descripcion": "Extracto estandarizado de Ginkgo con flavonoides y terpenlactonas; mejora flujo sanguineo retiniano y optico.",
        "mecanismoAccion": "Aumenta flujo sanguineo ocular, actividad antioxidante y neuroproteccion del nervio optico; inhibe PAF (factor activador plaquetario).",
        "nivelEvidencia": "B",
        "parteUsada": "hoja (extracto EGB 761, 24% flavonas, 6% terpenos)",
        "formasPresentacion": ["Capsulas (extracto estandarizado)"],
        "tiempoEfecto": "4-8 semanas",
        "duracionTratamiento": "3-6 meses",
        "advertencias": ["Riesgo de sangrado con anticoagulantes", "Suspender antes de cirugia"],
        "interaccionesMedicamentosas": ["Warfarina", "AAS", "Anticoagulantes", "ISRS"],
        "tags": ["ginkgo", "glaucoma", "flujo ocular", "neuroproteccion", "EGB 761"],
        "metadata": {"fechaCreacion": "2026-08-10", "fuente": "Cochrane Database + Phytother. Res."}
    },
    {
        "id": "goldenrod",
        "nombre": "Solidago (Vara de Oro)",
        "nombresAlternativos": ["Solidago canadensis", "Goldenrod", "Vara de oro europea"],
        "nombreCientifico": "Solidago virgaurea",
        "familia": "Asteraceae",
        "categoria": "fitoterapia",
        "sistemas": ["urinario"],
        "indicaciones": ["infeccion urinaria", "calculos renales", "inflamacion urinaria", "diuretico"],
        "descripcion": "Planta diuretica y antiinflamatoria de vias urinarias; usada en cistitis y prevencion de litiasis.",
        "mecanismoAccion": "Diuretico osmotico, antiseptico urinario (saponinas triterpenicas), antiinflamatorio via inhibicion COX-2; estimula eliminacion de bacterias.",
        "nivelEvidencia": "C",
        "parteUsada": "sumidad aerea",
        "formasPresentacion": ["Tintura", "Capsulas", "Infusion"],
        "tiempoEfecto": "24-48 horas (diuretico)",
        "duracionTratamiento": "1-3 semanas",
        "advertencias": ["Contraindicado en edema por insuficiencia cardiaca/renal", "Evitar en embarazo"],
        "interaccionesMedicamentosas": ["Diureticos (efecto aditivo)", "Litio"],
        "tags": ["diuretico", "cistitis", "litiasis", "antiseptico urinario"],
        "metadata": {"fechaCreacion": "2026-08-10", "fuente": "EMA HMPC monograph + ESCOP"}
    },
    {
        "id": "diente_leon_raiz",
        "nombre": "Diente de Leon (Raiz)",
        "nombresAlternativos": ["Dandelion root", "Taraxacum", "Amargon raiz", "Radicchina"],
        "nombreCientifico": "Taraxacum officinale",
        "familia": "Asteraceae",
        "categoria": "fitoterapia",
        "sistemas": ["hepatico", "urinario", "digestivo"],
        "indicaciones": ["detox", "digestion", "diuretico", "estrenimiento", "higado graso"],
        "descripcion": "Raiz amarga con inulina y taraxacina; colagogo, hepatoprotector y diuretico potasico.",
        "mecanismoAccion": "Estimula produccion de bilis (colagogo/coleretico), diuretico potasico sin deplecion, prebiotico por inulina.",
        "nivelEvidencia": "C",
        "parteUsada": "raiz",
        "formasPresentacion": ["Decoccion", "Capsulas", "Extracto seco"],
        "tiempoEfecto": "1-2 semanas",
        "duracionTratamiento": "2-4 semanas",
        "advertencias": ["Contraindicado en obstruccion biliar", "Calculos biliares sintomaticos"],
        "interaccionesMedicamentosas": ["Diureticos", "Antiarrítmicos (potasio)"],
        "tags": ["hepatoprotector", "diuretico", "coleretico", "prebiotico", "amargo"],
        "metadata": {"fechaCreacion": "2026-08-10", "fuente": "ESCOP monograph + Phytother. Res."}
    },
    {
        "id": "quercetina_urinario",
        "nombre": "Quercetina (Extracto)",
        "nombresAlternativos": ["Quercetin", "Soforetina", "3,3',4',5,7-pentahidroxiflavona"],
        "nombreCientifico": "Quercetin (flavonoide)",
        "familia": "Flavonoide (flavonol)",
        "categoria": "vitamina",
        "sistemas": ["urinario", "inmune", "cardiovascular"],
        "indicaciones": ["inflamacion urinaria", "prostatitis", "antioxidante", "alergia", "inmunidad"],
        "descripcion": "Flavonoide con accion antiinflamatoria, antihistaminica y antioxidante; util en cistitis intersticial y prostatitis.",
        "mecanismoAccion": "Inhibe enzimas pro-inflamatorias (COX-2, LOX, iNOS), estabiliza mastocitos (antihistaminico), antioxidante potente.",
        "nivelEvidencia": "B",
        "parteUsada": "Extracto natural (cascara de cebolla, manzana)",
        "formasPresentacion": ["Capsulas (300-1000mg)"],
        "tiempoEfecto": "2-4 semanas",
        "duracionTratamiento": "4-12 semanas",
        "advertencias": ["Puede reducir absorcion de antibioticos fluoroquinolonas"],
        "interaccionesMedicamentosas": ["Fluoroquinolonas", "Ciclosporina", "Estrogenos"],
        "tags": ["flavonoide", "antiinflamatorio", "antihistaminico", "cistitis intersticial", "prostatitis"],
        "metadata": {"fechaCreacion": "2026-08-10", "fuente": "J. Urol. + Cochrane reviews"}
    },
    {
        "id": "maca_negra",
        "nombre": "Maca Negra",
        "nombresAlternativos": ["Black Maca", "Lepidium meyenii negra", "Maca andina negra"],
        "nombreCientifico": "Lepidium meyenii",
        "familia": "Brassicaceae",
        "categoria": "fitoterapia",
        "sistemas": ["reproductivo", "endocrino"],
        "indicaciones": ["libido", "fertilidad", "energia", "hormonal"],
        "descripcion": "Variedad negra de Maca andina; mejora fertilidad masculina, libido y energia sin efectos hormonales directos.",
        "mecanismoAccion": "Adaptogeno: modula eje HHA, mejora calidad espermatica (motilidad y volumen), sin alterar testosterona directamente.",
        "nivelEvidencia": "B",
        "parteUsada": "raiz (gelatinizada)",
        "formasPresentacion": ["Polvo gelatinizado", "Capsulas (extracto)"],
        "tiempoEfecto": "2-4 semanas",
        "duracionTratamiento": "8-12 semanas",
        "advertencias": ["Insuficiente evidencia en embarazo/lactancia"],
        "interaccionesMedicamentosas": [],
        "tags": ["adaptogeno", "fertilidad masculina", "libido", "energia", "andina"],
        "metadata": {"fechaCreacion": "2026-08-10", "fuente": "Andrologia + Evid Based Complement Alternat Med"}
    },
    {
        "id": "coq10_fertilidad",
        "nombre": "Coenzima Q10 (Fertilidad)",
        "nombresAlternativos": ["Ubiquinona", "CoQ10", "Q10", "Ubidecarenona"],
        "nombreCientifico": "Coenzima Q10",
        "familia": "Quinona (ubiquinona)",
        "categoria": "vitamina",
        "sistemas": ["reproductivo", "cardiovascular", "metabolico"],
        "indicaciones": ["fertilidad", "energia", "antioxidante", "cardioproteccion", "mitocondrias"],
        "descripcion": "Antioxidante mitocondrial clave; mejora calidad ovocitaria y motilidad espermatica; protector cardiovascular.",
        "mecanismoAccion": "Cofactor de la cadena de transporte de electrones (ATP), antioxidante liposoluble en membranas, recicla vitamina E.",
        "nivelEvidencia": "A",
        "parteUsada": "Sintesis/fermentacion",
        "formasPresentacion": ["Capsulas blandas (ubiquinona/ubiquinol)"],
        "tiempoEfecto": "4-12 semanas",
        "duracionTratamiento": "3-6 meses (fertilidad)",
        "advertencias": ["Reduce efecto de warfarina", "Suspender 2 dias antes de cirugia"],
        "interaccionesMedicamentosas": ["Warfarina", "Estatinas (pueden reducir niveles)"],
        "tags": ["antioxidante", "mitocondrias", "ATP", "fertilidad", "cardio"],
        "metadata": {"fechaCreacion": "2026-08-10", "fuente": "Cochrane reviews + Fertil Steril meta-analisis"}
    },
    {
        "id": "picrorrhiza",
        "nombre": "Picrorhiza",
        "nombresAlternativos": ["Picrorhiza kurroa", "Kutki", "Picrorhiza raiz"],
        "nombreCientifico": "Picrorhiza kurroa",
        "familia": "Plantaginaceae",
        "categoria": "fitoterapia",
        "sistemas": ["hepatico", "inmune"],
        "indicaciones": ["higado graso", "detox", "hepatitis", "antioxidante", "inmunidad"],
        "descripcion": "Raiz ayurvedica con iridoides (picrosidos I/II); hepatoprotector e inmunomodulador potente.",
        "mecanismoAccion": "Estimula regeneracion hepatica, antioxidante, antiinflamatorio (via NF-kB), inmunomodulador; protege contra hepatotoxinas.",
        "nivelEvidencia": "B",
        "parteUsada": "raiz",
        "formasPresentacion": ["Capsulas (extracto estandarizado)"],
        "tiempoEfecto": "4-8 semanas",
        "duracionTratamiento": "8-12 semanas",
        "advertencias": ["Evitar en embarazo", "Puede reducir absorcion de hierro"],
        "interaccionesMedicamentosas": ["Hierro", "Inmunosupresores"],
        "tags": ["hepatoprotector", "iridoide", "kutki", "inmunomodulador", "NAFLD"],
        "metadata": {"fechaCreacion": "2026-08-10", "fuente": "Phytother. Res. + J. Clin. Gastroenterol."}
    },
    {
        "id": "regaliz_dgl",
        "nombre": "Regaliz DGL (Deglicirrizado)",
        "nombresAlternativos": ["DGL", "Deglycyrrhizinated Licorice", "Glycyrrhiza glabra DGL"],
        "nombreCientifico": "Glycyrrhiza glabra (sin glicirricina)",
        "familia": "Fabaceae",
        "categoria": "fitoterapia",
        "sistemas": ["digestivo", "hepatico", "respiratorio"],
        "indicaciones": ["ulceras", "gastritis", "reflujo", "esofago de Barrett", "tos"],
        "descripcion": "Extracto de regaliz sin glicirricina (DGL) para evitar hipertension; protector de mucosa gastrica y esofagica.",
        "mecanismoAccion": "Flavonoides (licoflavidina) estimulan mucina y prostaglandinas protectoras gastricas; antiespasmodico; antiinflamatorio topico.",
        "nivelEvidencia": "B",
        "parteUsada": "raiz (deglicirrizada)",
        "formasPresentacion": ["Tabletas masticables", "Polvo DGL"],
        "tiempoEfecto": "1-2 semanas",
        "duracionTratamiento": "4-8 semanas",
        "advertencias": ["DGL generalmente sin efectos de regaliz normal", "Alergia rara"],
        "interaccionesMedicamentosas": ["Antihipertensivos (DGL tiene minimo efecto)"],
        "tags": ["DGL", "gastritis", "reflujo", "mucosa", "protector gastrico"],
        "metadata": {"fechaCreacion": "2026-08-10", "fuente": "Gut + BMJ Evidence-Based Med"}
    },
    {
        "id": "n_acetilcisteina_hepatico",
        "nombre": "N-Acetilcisteina (NAC)",
        "nombresAlternativos": ["NAC", "N-Acetylcysteine", "Acetilcisteina"],
        "nombreCientifico": "N-Acetilcisteina",
        "familia": "Aminoacido (derivado de cisteina)",
        "categoria": "aminoacido",
        "sistemas": ["hepatico", "respiratorio", "inmune"],
        "indicaciones": ["higado graso", "detox", "antioxidante", "mucolitico", "inmunidad"],
        "descripcion": "Precursor de glutation; hepatoprotector (antidoto paracetamol), mucolitico y antioxidante sistemico.",
        "mecanismoAccion": "Donador de cisteina recarga glutation (GSH); rompe enlaces disulfuro en moco; antioxidante directo.",
        "nivelEvidencia": "A",
        "parteUsada": "Sintesis",
        "formasPresentacion": ["Capsulas (600mg)", "Polvo", "Solucion oral/efervescente"],
        "tiempoEfecto": "1-3 horas (agudo), 4-8 semanas (cronico)",
        "duracionTratamiento": "4-12 semanas (hepatico)",
        "advertencias": ["Nauseas comunes", "Olor a azufre", "Posible reaccion anafilactoide IV"],
        "interaccionesMedicamentosas": ["Nitroglicerina (hipotension)", "Carbon activado (reduce absorcion)"],
        "tags": ["glutation", "antioxidante", "hepatoprotector", "mucolitico", "NAC"],
        "metadata": {"fechaCreacion": "2026-08-10", "fuente": "Cochrane reviews + Hepatology"}
    },
    {
        "id": "guggul",
        "nombre": "Guggul",
        "nombresAlternativos": ["Guggulipid", "Commiphora mukul", "Guggulu", "Goma guggul"],
        "nombreCientifico": "Commiphora wightii",
        "familia": "Burseraceae",
        "categoria": "fitoterapia",
        "sistemas": ["endocrino", "cardiovascular", "metabolico"],
        "indicaciones": ["colesterol", "hipotiroidismo", "obesidad", "articular"],
        "descripcion": "Resina ayurvedica con guggulsteronas; hipolipemiante y estimulante tiroideo suave.",
        "mecanismoAccion": "Guggulsteronas estimulan tiroides (T3/T4), reducen colesterol via FXR y aumento de receptores hepaticos LDL; antiinflamatorio.",
        "nivelEvidencia": "B",
        "parteUsada": "resina (goma oleosa)",
        "formasPresentacion": ["Capsulas (extracto estandarizado guggulsteronas)"],
        "tiempoEfecto": "4-8 semanas",
        "duracionTratamiento": "12 semanas",
        "advertencias": ["Puede causar dispepsia", "Evitar en hipertiroidismo", "Interaccion con hormonas tiroideas"],
        "interaccionesMedicamentosas": ["Levotiroxina", "Estatinas", "Anticoagulantes"],
        "tags": ["guggulsteronas", "hipolipemiante", "tiroides", "ayurveda", "colesterol"],
        "metadata": {"fechaCreacion": "2026-08-10", "fuente": "J. Assoc. Physicians India + Cardiovasc. Drugs Rev."}
    },
    {
        "id": "gymnema_sylvestre",
        "nombre": "Gymnema Sylvestre",
        "nombresAlternativos": ["Gurmar", "Destructor de azucar", "Gymnema", "Asclepiadaceae"],
        "nombreCientifico": "Gymnema sylvestre",
        "familia": "Apocynaceae",
        "categoria": "fitoterapia",
        "sistemas": ["endocrino", "metabolico"],
        "indicaciones": ["diabetes", "glucosa", "ansiedad por dulces", "obesidad"],
        "descripcion": "Planta gurmar (destructor de azucar); reduce deseo por dulces y ayuda a controlar glucemia.",
        "mecanismoAccion": "Acido gymnemico bloquea receptores de dulzor en lengua; aumenta regeneracion de celulas beta-pancreaticas; mejora sensibilidad a insulina.",
        "nivelEvidencia": "B",
        "parteUsada": "hoja",
        "formasPresentacion": ["Capsulas (extracto 25% gymnemico)", "Tintura", "Polvo"],
        "tiempoEfecto": "Inmediato (dulzor), 4-12 semanas (glucosa)",
        "duracionTratamiento": "3-6 meses",
        "advertencias": ["Riesgo de hipoglucemia con insulina/sulfonilureas", "Evitar en embarazo"],
        "interaccionesMedicamentosas": ["Insulina", "Metformina", "Sulfonilureas"],
        "tags": ["gurmar", "glucosa", "diabetes", "antidiabetico", "suprime dulzor"],
        "metadata": {"fechaCreacion": "2026-08-10", "fuente": "J. Ethnopharmacol. + Diabetes Care"}
    },
    {
        "id": "kelp_yodo",
        "nombre": "Kelp (Yodo)",
        "nombresAlternativos": ["Fucus vesiculosus", "Alga parda", "Yodo marino", "Kombu"],
        "nombreCientifico": "Fucus vesiculosus",
        "familia": "Fucaceae (algas pardas)",
        "categoria": "fitoterapia",
        "sistemas": ["endocrino", "metabolico"],
        "indicaciones": ["hipotiroidismo", "bocio", "metabolismo", "obesidad"],
        "descripcion": "Alga parda rica en yodo organico; soporte nutricional de tiroides en deficiencia de yodo.",
        "mecanismoAccion": "Yodo organanico es precursor de T3/T4; fucoidanos con actividad antioxidante y metabolica.",
        "nivelEvidencia": "C",
        "parteUsada": "talo (alga entera)",
        "formasPresentacion": ["Capsulas (polvo)", "Tabletas estandarizadas en yodo"],
        "tiempoEfecto": "4-8 semanas",
        "duracionTratamiento": "3-6 meses",
        "advertencias": ["Peligro en hipertiroidismo/Graves", "Sobredosis de yodo desencadena tiroiditis", "Evitar en embarazo sin supervision"],
        "interaccionesMedicamentosas": ["Levotiroxina", "Antitiroideos (metimazol/PTU)", "Litio"],
        "tags": ["yodo", "tiroides", "alga", "bocio", "metabolismo"],
        "metadata": {"fechaCreacion": "2026-08-10", "fuente": "WHO/UNICEF yodo + J. Thyroid Res."}
    },
    {
        "id": "selenio_tiroideo",
        "nombre": "Selenio (Metionina, Tiroideo)",
        "nombresAlternativos": ["Selenio L-metionina", "Selenium", "Se"],
        "nombreCientifico": "Selenio (L-selenometionina)",
        "familia": "Oligoelemento",
        "categoria": "mineral",
        "sistemas": ["endocrino", "inmune"],
        "indicaciones": ["hipotiroidismo", "Hashimoto", "antioxidante", "inmunidad"],
        "descripcion": "Cofactor de desyodinasas (T4->T3) y glutation peroxidasa; esencial en tiroiditis autoinmune.",
        "mecanismoAccion": "Cofactor de desyodinasas tipo 1/2/3, esencial para conversion T4->T3; antioxidante via glutation peroxidasa y tioredoxina reductasa.",
        "nivelEvidencia": "A",
        "parteUsada": "Sintesis/levadura enriquecida",
        "formasPresentacion": ["Capsulas (L-selenometionina 55-200mcg)"],
        "tiempoEfecto": "8-12 semanas",
        "duracionTratamiento": "6-12 meses (Hashimoto)",
        "advertencias": ["Toxicidad >400mcg/dia (selenosis)", "Alopecia, unas fragiles"],
        "interaccionesMedicamentosas": ["Anticoagulantes (alto riesgo)"],
        "tags": ["selenio", "tiroides", "Hashimoto", "antioxidante", "desyodinasa"],
        "metadata": {"fechaCreacion": "2026-08-10", "fuente": "Thyroid (ATA) + Cochrane Hashimoto"}
    },
    {
        "id": "vitamina_k2_mk7",
        "nombre": "Vitamina K2 (MK-7)",
        "nombresAlternativos": ["Menaquinona-7", "MK-7", "K2"],
        "nombreCientifico": "Menaquinona-7 (MK-7)",
        "familia": "Vitamina liposoluble (naftoquinona)",
        "categoria": "vitamina",
        "sistemas": ["cardiovascular", "musculoesqueletico"],
        "indicaciones": ["osteoporosis", "calcificacion vascular", "coagulacion", "cardioproteccion"],
        "descripcion": "Menaquinona de cadena larga (MK-7) con vida media larga; activa osteocalcina y matriz-Gla, dirige calcio a hueso y fuera de arterias.",
        "mecanismoAccion": "Cofactor de gamma-carboxilacion: activa osteocalcina (hueso) y MGP (inhibe calcificacion vascular); sinergia con vitamina D3.",
        "nivelEvidencia": "B",
        "parteUsada": "Fermentacion (Bacillus subtilis natto)",
        "formasPresentacion": ["Capsulas blandas (MK-7 45-180mcg)"],
        "tiempoEfecto": "8-12 semanas",
        "duracionTratamiento": "Continuo (cronico)",
        "advertencias": ["Interfiere con anticoagulantes cumarinicos (warfarina)", "Suspender antes de cirugia"],
        "interaccionesMedicamentosas": ["Warfarina", "Acenocumarol"],
        "tags": ["MK-7", "menaquinona", "hueso", "calcificacion vascular", "K2"],
        "metadata": {"fechaCreacion": "2026-08-10", "fuente": "Osteoporosis Int. + Thromb. Res."}
    },
    {
        "id": "ipriflavona",
        "nombre": "Ipriflavona",
        "nombresAlternativos": ["Ipriflavone", "Ostivone", "IP", "7-isopropoxi-isoflavona"],
        "nombreCientifico": "7-isopropoxi-isoflavona",
        "familia": "Isoflavona sintetica",
        "categoria": "vitamina",
        "sistemas": ["musculoesqueletico", "endocrino"],
        "indicaciones": ["osteoporosis", "menopausia", "hueso"],
        "descripcion": "Isoflavona sintetica que inhibe resorcion osea y mimetiza estrogeno sin efecto proliferativo uterino.",
        "mecanismoAccion": "Inhibe osteoclastogenesis (efecto anti-resortivo), estimula osteoblastos; debil fitoestrogeno sin proliferacion endometrial.",
        "nivelEvidencia": "B",
        "parteUsada": "Sintesis",
        "formasPresentacion": ["Capsulas (200mg x3/dia)"],
        "tiempoEfecto": "6-12 meses",
        "duracionTratamiento": "1-2 años",
        "advertencias": ["Reduce recuento linfocitario con uso >6 meses (raro)", "Evitar en inmunodeprimidos"],
        "interaccionesMedicamentosas": ["Teofilina (reduce clearance)", "Warfarina", "Levodopa"],
        "tags": ["isoflavona", "osteoporosis", "menopausia", "anti-resortivo"],
        "metadata": {"fechaCreacion": "2026-08-10", "fuente": "Calcif. Tissue Int. + Menopause"}
    },
]

for ing in new_ingredientes:
    if ing['id'] in existing_ids:
        raise ValueError(f"ID duplicado: {ing['id']}")
    existing_ids.add(ing['id'])

fito_new = [i for i in new_ingredientes if i['categoria'] == 'fitoterapia']
vit_new = [i for i in new_ingredientes if i['categoria'] in ('vitamina','mineral','aminoacido')]

fito_path = DATA_DIR / 'fitoterapia.json'
fito_data = json.load(open(fito_path))
fito_data['ingredientes'].extend(fito_new)
fito_data['metadata']['total'] = len(fito_data['ingredientes'])
fito_data['metadata']['ultimaActualizacion'] = '2026-08-10'
json.dump(fito_data, open(fito_path, 'w'), indent=2, ensure_ascii=False)

vit_path = DATA_DIR / 'vitaminas_minerales.json'
vit_data = json.load(open(vit_path))
vit_data['ingredientes'].extend(vit_new)
vit_data['metadata']['total'] = len(vit_data['ingredientes'])
vit_data['metadata']['ultimaActualizacion'] = '2026-08-10'
json.dump(vit_data, open(vit_path, 'w'), indent=2, ensure_ascii=False)

print(f"Fitoterapia: +{len(fito_new)} ingredientes (total: {len(fito_data['ingredientes'])})")
print(f"Vitaminas/Minerales: +{len(vit_new)} ingredientes (total: {len(vit_data['ingredientes'])})")
print(f"Total nuevos: {len(new_ingredientes)}")
